-- GENERADO por packages/catalog-data (pnpm seed). No editar a mano:
-- corregir los JSON de packages/catalog-data/data, validar y volver a generar.
-- Incluye los precios DE EJEMPLO (sample-prices.json); los reales llegan con el seed del scraper.

insert into public.store (id, name, slug, active) values
  ('store-alsuper', 'Alsuper', 'alsuper', true),
  ('store-walmart', 'Walmart', 'walmart', true),
  ('store-soriana', 'Soriana', 'soriana', true)
on conflict do nothing;

insert into public.canonical_product (id, name, unit_type, category, allergens) values
  ('cp-pechuga-de-pollo', 'Pechuga de pollo', 'mass_g', 'proteina', '{}'),
  ('cp-huevo', 'Huevo', 'unit', 'huevo', '{"huevo"}'),
  ('cp-frijol-pinto', 'Frijol pinto', 'mass_g', 'leguminosa', '{}'),
  ('cp-arroz', 'Arroz', 'mass_g', 'arroz', '{}'),
  ('cp-pasta-spaghetti', 'Pasta spaghetti', 'mass_g', 'pasta', '{"gluten"}'),
  ('cp-avena', 'Avena', 'mass_g', 'cereal', '{"gluten"}'),
  ('cp-tortilla-de-maiz', 'Tortilla de maíz', 'mass_g', 'tortilla', '{}'),
  ('cp-jitomate', 'Jitomate', 'mass_g', 'jitomate', '{}'),
  ('cp-cebolla-blanca', 'Cebolla blanca', 'unit', 'cebolla', '{}'),
  ('cp-ajo-dientes', 'Ajo (dientes)', 'unit', 'ajo', '{}'),
  ('cp-chile-serrano', 'Chile serrano', 'unit', 'chile', '{}'),
  ('cp-cilantro', 'Cilantro', 'mass_g', 'hierba', '{}'),
  ('cp-platano', 'Plátano', 'unit', 'fruta', '{}'),
  ('cp-leche-entera', 'Leche entera', 'volume_ml', 'leche', '{"lácteos"}'),
  ('cp-queso-fresco', 'Queso fresco', 'mass_g', 'queso', '{"lácteos"}'),
  ('cp-crema', 'Crema', 'volume_ml', 'crema', '{"lácteos"}'),
  ('cp-aceite-vegetal', 'Aceite vegetal', 'volume_ml', 'aceite', '{}'),
  ('cp-sal', 'Sal', 'mass_g', 'sal', '{}'),
  ('cp-carne-molida-de-res', 'Carne molida de res', 'mass_g', 'proteina', '{}'),
  ('cp-atun-en-agua', 'Atún en agua', 'mass_g', 'proteina', '{"pescado"}'),
  ('cp-tofu-firme', 'Tofu firme', 'mass_g', 'proteina', '{"soya"}'),
  ('cp-lentejas', 'Lentejas', 'mass_g', 'leguminosa', '{}'),
  ('cp-garbanzo', 'Garbanzo', 'mass_g', 'leguminosa', '{}'),
  ('cp-bolillo', 'Bolillo', 'unit', 'pan', '{"gluten"}'),
  ('cp-pan-de-caja', 'Pan de caja', 'mass_g', 'pan', '{"gluten"}'),
  ('cp-pasta-de-codo', 'Pasta de codo', 'mass_g', 'pasta', '{"gluten"}'),
  ('cp-fideo', 'Fideo', 'mass_g', 'pasta', '{"gluten"}'),
  ('cp-tortilla-de-harina', 'Tortilla de harina', 'mass_g', 'tortilla', '{"gluten"}'),
  ('cp-papa', 'Papa', 'mass_g', 'verdura', '{}'),
  ('cp-zanahoria', 'Zanahoria', 'mass_g', 'verdura', '{}'),
  ('cp-calabacita', 'Calabacita', 'mass_g', 'verdura', '{}'),
  ('cp-brocoli', 'Brócoli', 'mass_g', 'verdura', '{}'),
  ('cp-chile-poblano', 'Chile poblano', 'unit', 'chile', '{}'),
  ('cp-pimiento-morron', 'Pimiento morrón', 'unit', 'chile', '{}'),
  ('cp-lechuga', 'Lechuga', 'unit', 'hoja', '{}'),
  ('cp-aguacate', 'Aguacate', 'unit', 'aguacate', '{}'),
  ('cp-limon', 'Limón', 'unit', 'citrico', '{}'),
  ('cp-manzana', 'Manzana', 'unit', 'fruta', '{}'),
  ('cp-queso-oaxaca', 'Queso Oaxaca', 'mass_g', 'queso', '{"lácteos"}'),
  ('cp-yogur-natural', 'Yogur natural', 'mass_g', 'yogur', '{"lácteos"}'),
  ('cp-mantequilla', 'Mantequilla', 'mass_g', 'grasa', '{"lácteos"}'),
  ('cp-salsa-de-soya', 'Salsa de soya', 'volume_ml', 'salsa', '{"soya","gluten"}'),
  ('cp-oregano', 'Orégano', 'mass_g', 'condimento seco', '{}'),
  ('cp-azucar', 'Azúcar', 'mass_g', 'azucar', '{}'),
  ('cp-aceite-de-oliva', 'Aceite de oliva', 'volume_ml', 'aceite', '{}'),
  ('cp-pure-de-tomate', 'Puré de tomate', 'mass_g', 'jitomate', '{}')
on conflict do nothing;

insert into public.colloquial_unit (term, base_quantity, base_unit) values
  ('pizca', 1, 'mass_g'),
  ('cucharadita', 5, 'volume_ml'),
  ('cucharada', 15, 'volume_ml'),
  ('taza', 240, 'volume_ml')
on conflict do nothing;

insert into public.recipe (id, name, cuisine, meal_type, tags, prep_time_minutes, servings_base, allergens) values
  ('rec-tacos-de-pollo', 'Tacos de pollo', 'Mexicana', '{"comida","cena"}', '{"rápida","alta en proteína"}', 25, 4, '{}'),
  ('rec-arroz-con-pollo', 'Arroz con pollo', 'Mexicana', '{"comida"}', '{"alta en proteína"}', 45, 4, '{}'),
  ('rec-huevos-a-la-mexicana', 'Huevos a la mexicana', 'Mexicana', '{"desayuno","cena"}', '{"rápida","económica"}', 15, 2, '{"huevo"}'),
  ('rec-spaghetti-con-jitomate', 'Spaghetti con jitomate', 'Italiana', '{"comida","cena"}', '{"económica"}', 30, 4, '{"gluten","lácteos"}'),
  ('rec-enfrijoladas', 'Enfrijoladas', 'Mexicana', '{"comida","cena"}', '{"económica"}', 35, 4, '{"lácteos"}'),
  ('rec-avena-con-platano', 'Avena con plátano', 'Mexicana', '{"desayuno"}', '{"rápida","económica"}', 10, 2, '{"gluten","lácteos"}'),
  ('rec-chilaquiles-rojos', 'Chilaquiles rojos', 'Mexicana', '{"desayuno"}', '{"económica"}', 30, 4, '{"lácteos"}'),
  ('rec-molletes-con-pico-de-gallo', 'Molletes con pico de gallo', 'Mexicana', '{"desayuno","cena"}', '{"rápida","para niños"}', 20, 4, '{"gluten","lácteos"}'),
  ('rec-huevos-rancheros', 'Huevos rancheros', 'Mexicana', '{"desayuno"}', '{"rápida","alta en proteína"}', 20, 2, '{"huevo"}'),
  ('rec-pan-frances', 'Pan francés', 'Casera básica', '{"desayuno"}', '{"para niños"}', 15, 4, '{"gluten","huevo","lácteos"}'),
  ('rec-yogur-con-manzana-y-avena', 'Yogur con manzana y avena', 'Casera básica', '{"desayuno","snack"}', '{"rápida","ligera"}', 5, 2, '{"gluten","lácteos"}'),
  ('rec-omelette-de-verduras', 'Omelette de verduras', 'Casera básica', '{"desayuno","cena"}', '{"vegetariana","ligera","rápida"}', 15, 2, '{"huevo"}'),
  ('rec-licuado-de-platano-con-avena', 'Licuado de plátano con avena', 'Casera básica', '{"desayuno","snack"}', '{"rápida","para niños"}', 5, 2, '{"gluten","lácteos"}'),
  ('rec-tinga-de-pollo', 'Tinga de pollo', 'Mexicana', '{"comida","cena"}', '{"alta en proteína"}', 45, 4, '{"lácteos"}'),
  ('rec-picadillo', 'Picadillo', 'Mexicana', '{"comida"}', '{"alta en proteína","económica"}', 35, 4, '{}'),
  ('rec-calabacitas-a-la-mexicana', 'Calabacitas a la mexicana', 'Mexicana', '{"comida","cena"}', '{"vegetariana","ligera","económica"}', 25, 4, '{}'),
  ('rec-rajas-con-crema', 'Rajas con crema', 'Mexicana', '{"comida","cena"}', '{"vegetariana"}', 35, 4, '{"lácteos"}'),
  ('rec-quesadillas', 'Quesadillas', 'Mexicana', '{"cena","snack"}', '{"rápida","para niños"}', 15, 4, '{"lácteos"}'),
  ('rec-enchiladas-rojas-de-pollo', 'Enchiladas rojas de pollo', 'Mexicana', '{"comida","cena"}', '{"alta en proteína"}', 50, 4, '{"lácteos"}'),
  ('rec-burritos-de-frijol-con-queso', 'Burritos de frijol con queso', 'Mexicana', '{"comida","cena"}', '{"rápida","económica"}', 20, 4, '{"gluten","lácteos"}'),
  ('rec-arroz-rojo', 'Arroz rojo', 'Mexicana', '{"comida"}', '{"vegetariana","económica"}', 35, 4, '{}'),
  ('rec-guacamole-con-tostadas-caseras', 'Guacamole con tostadas caseras', 'Mexicana', '{"snack"}', '{"vegetariana","rápida"}', 20, 4, '{}'),
  ('rec-sopa-de-fideo', 'Sopa de fideo', 'Casera básica', '{"comida"}', '{"económica","para niños"}', 25, 4, '{"gluten"}'),
  ('rec-caldo-de-pollo-con-verduras', 'Caldo de pollo con verduras', 'Casera básica', '{"comida"}', '{"ligera","alta en proteína"}', 50, 4, '{}'),
  ('rec-lentejas-guisadas', 'Lentejas guisadas', 'Casera básica', '{"comida"}', '{"vegetariana","económica"}', 45, 4, '{}'),
  ('rec-sopa-de-codito', 'Sopa de codito', 'Casera básica', '{"comida"}', '{"económica","para niños"}', 25, 4, '{"gluten"}'),
  ('rec-pollo-a-la-plancha-con-verduras', 'Pollo a la plancha con verduras', 'Casera básica', '{"comida","cena"}', '{"alta en proteína","ligera"}', 30, 4, '{}'),
  ('rec-ensalada-de-atun', 'Ensalada de atún', 'Casera básica', '{"comida","cena"}', '{"ligera","rápida","alta en proteína"}', 15, 2, '{"pescado"}'),
  ('rec-ensalada-de-coditos-con-atun', 'Ensalada de coditos con atún', 'Casera básica', '{"comida"}', '{"económica"}', 25, 4, '{"gluten","lácteos","pescado"}'),
  ('rec-crema-de-calabacita', 'Crema de calabacita', 'Casera básica', '{"comida","cena"}', '{"vegetariana","ligera"}', 30, 4, '{"lácteos"}'),
  ('rec-sandwich-de-atun', 'Sándwich de atún', 'Casera básica', '{"cena","snack"}', '{"rápida"}', 10, 2, '{"gluten","pescado"}'),
  ('rec-spaghetti-a-la-bolonesa', 'Spaghetti a la boloñesa', 'Italiana', '{"comida","cena"}', '{"alta en proteína"}', 40, 4, '{"gluten"}'),
  ('rec-pasta-con-verduras', 'Pasta con verduras', 'Italiana', '{"comida","cena"}', '{"vegetariana"}', 30, 4, '{"gluten","lácteos"}'),
  ('rec-arroz-frito-con-verduras', 'Arroz frito con verduras', 'Asiática', '{"comida","cena"}', '{"económica","rápida"}', 25, 4, '{"gluten","huevo","soya"}'),
  ('rec-pollo-teriyaki', 'Pollo teriyaki', 'Asiática', '{"comida","cena"}', '{"alta en proteína"}', 35, 4, '{"gluten","soya"}'),
  ('rec-tofu-salteado-con-verduras', 'Tofu salteado con verduras', 'Asiática', '{"comida","cena"}', '{"vegetariana"}', 30, 4, '{"gluten","soya"}'),
  ('rec-ensalada-de-garbanzo', 'Ensalada de garbanzo', 'Mediterránea', '{"comida","cena"}', '{"vegetariana","ligera"}', 20, 4, '{}'),
  ('rec-pollo-al-horno-con-papas', 'Pollo al horno con papas', 'Mediterránea', '{"comida"}', '{"alta en proteína"}', 60, 4, '{}'),
  ('rec-lentejas-con-arroz', 'Lentejas con arroz', 'Mediterránea', '{"comida","cena"}', '{"vegetariana","económica"}', 45, 4, '{}'),
  ('rec-manzana-con-yogur', 'Manzana con yogur', 'Casera básica', '{"snack"}', '{"rápida","ligera","para niños"}', 5, 2, '{"lácteos"}')
on conflict do nothing;

insert into public.recipe_step (id, recipe_id, step_order, title, content, timer_seconds) values
  ('rec-tacos-de-pollo-step-1', 'rec-tacos-de-pollo', 1, 'Cocer el pollo', 'Pon la pechuga en una olla con agua y sal. Deja hervir a fuego medio.', 900),
  ('rec-tacos-de-pollo-step-2', 'rec-tacos-de-pollo', 2, 'Deshebrar', 'Saca el pollo, deja que se enfríe un poco y deshébralo con dos tenedores.', null),
  ('rec-tacos-de-pollo-step-3', 'rec-tacos-de-pollo', 3, 'Picar', 'Pica la cebolla y el cilantro finamente.', null),
  ('rec-tacos-de-pollo-step-4', 'rec-tacos-de-pollo', 4, 'Calentar tortillas', 'Calienta las tortillas en un comal con un poco de aceite y arma los tacos.', 120),
  ('rec-arroz-con-pollo-step-1', 'rec-arroz-con-pollo', 1, 'Dorar el arroz', 'Calienta el aceite y dora el arroz hasta que se vea transparente.', 300),
  ('rec-arroz-con-pollo-step-2', 'rec-arroz-con-pollo', 2, 'Licuar', 'Licúa el jitomate con la cebolla, el ajo y una taza de agua.', null),
  ('rec-arroz-con-pollo-step-3', 'rec-arroz-con-pollo', 3, 'Cocer', 'Agrega el licuado, el pollo en trozos y sal. Tapa y cocina a fuego bajo.', 1500),
  ('rec-arroz-con-pollo-step-4', 'rec-arroz-con-pollo', 4, 'Reposar', 'Apaga el fuego y deja reposar tapado antes de servir.', 300),
  ('rec-huevos-a-la-mexicana-step-1', 'rec-huevos-a-la-mexicana', 1, 'Picar', 'Pica el jitomate, la cebolla y el chile serrano.', null),
  ('rec-huevos-a-la-mexicana-step-2', 'rec-huevos-a-la-mexicana', 2, 'Sofreír', 'Sofríe la verdura en aceite caliente.', 180),
  ('rec-huevos-a-la-mexicana-step-3', 'rec-huevos-a-la-mexicana', 3, 'Agregar huevo', 'Agrega los huevos batidos con sal y mueve hasta que cuajen.', 240),
  ('rec-spaghetti-con-jitomate-step-1', 'rec-spaghetti-con-jitomate', 1, 'Cocer la pasta', 'Hierve agua con sal y cuece la pasta.', 600),
  ('rec-spaghetti-con-jitomate-step-2', 'rec-spaghetti-con-jitomate', 2, 'Salsa', 'Sofríe el ajo en aceite, agrega el jitomate picado y cocina hasta que espese.', 600),
  ('rec-spaghetti-con-jitomate-step-3', 'rec-spaghetti-con-jitomate', 3, 'Servir', 'Mezcla la pasta con la salsa y sirve con queso desmoronado.', null),
  ('rec-enfrijoladas-step-1', 'rec-enfrijoladas', 1, 'Licuar frijoles', 'Licúa los frijoles cocidos con un poco de su caldo y cebolla.', null),
  ('rec-enfrijoladas-step-2', 'rec-enfrijoladas', 2, 'Calentar salsa', 'Calienta el licuado en una olla con sal hasta que hierva.', 300),
  ('rec-enfrijoladas-step-3', 'rec-enfrijoladas', 3, 'Pasar tortillas', 'Pasa las tortillas por aceite caliente y luego por la salsa de frijol.', null),
  ('rec-enfrijoladas-step-4', 'rec-enfrijoladas', 4, 'Servir', 'Dobla las tortillas y sirve con crema y queso.', null),
  ('rec-avena-con-platano-step-1', 'rec-avena-con-platano', 1, 'Hervir', 'Calienta la leche con la avena a fuego medio moviendo seguido.', 420),
  ('rec-avena-con-platano-step-2', 'rec-avena-con-platano', 2, 'Servir', 'Sirve y agrega el plátano en rodajas.', null),
  ('rec-chilaquiles-rojos-step-1', 'rec-chilaquiles-rojos', 1, 'Freír la tortilla', 'Corta las tortillas en triángulos y fríelas en aceite hasta que estén doradas, unos 8 minutos.', 480),
  ('rec-chilaquiles-rojos-step-2', 'rec-chilaquiles-rojos', 2, 'Hacer la salsa', 'Licúa el jitomate con media cebolla, el ajo, los chiles y sal. Cocina la salsa 10 minutos.', 600),
  ('rec-chilaquiles-rojos-step-3', 'rec-chilaquiles-rojos', 3, 'Bañar los totopos', 'Agrega los totopos a la salsa y mezcla hasta cubrirlos.', null),
  ('rec-chilaquiles-rojos-step-4', 'rec-chilaquiles-rojos', 4, 'Servir', 'Sirve con crema, queso desmoronado y aros de cebolla.', null),
  ('rec-molletes-con-pico-de-gallo-step-1', 'rec-molletes-con-pico-de-gallo', 1, 'Cocer los frijoles', 'Cuece los frijoles en agua con sal hasta que estén suaves y macháquelos.', 3600),
  ('rec-molletes-con-pico-de-gallo-step-2', 'rec-molletes-con-pico-de-gallo', 2, 'Armar', 'Parte los bolillos, úntales frijol y cúbrelos con queso deshebrado.', null),
  ('rec-molletes-con-pico-de-gallo-step-3', 'rec-molletes-con-pico-de-gallo', 3, 'Gratinar', 'Hornea o calienta en comal tapado hasta que el queso se derrita, unos 8 minutos.', 480),
  ('rec-molletes-con-pico-de-gallo-step-4', 'rec-molletes-con-pico-de-gallo', 4, 'Pico de gallo', 'Pica jitomate, cebolla, cilantro y chile, mezcla con sal y sirve encima.', null),
  ('rec-huevos-rancheros-step-1', 'rec-huevos-rancheros', 1, 'Salsa ranchera', 'Licúa jitomate, un trozo de cebolla, ajo y chile. Cocina la salsa con sal 8 minutos.', 480),
  ('rec-huevos-rancheros-step-2', 'rec-huevos-rancheros', 2, 'Calentar tortillas', 'Pasa las tortillas por aceite caliente sin que se doren.', null),
  ('rec-huevos-rancheros-step-3', 'rec-huevos-rancheros', 3, 'Estrellar huevos', 'Fríe los huevos a tu gusto, unos 3 minutos.', 180),
  ('rec-huevos-rancheros-step-4', 'rec-huevos-rancheros', 4, 'Servir', 'Pon los huevos sobre las tortillas y báñalos con la salsa.', null),
  ('rec-pan-frances-step-1', 'rec-pan-frances', 1, 'Mezclar', 'Bate los huevos con la leche y la mitad del azúcar.', null),
  ('rec-pan-frances-step-2', 'rec-pan-frances', 2, 'Remojar', 'Pasa cada rebanada de pan por la mezcla, sin dejar que se deshaga.', null),
  ('rec-pan-frances-step-3', 'rec-pan-frances', 3, 'Dorar', 'Dora el pan en mantequilla a fuego medio, 2 minutos por lado.', 240),
  ('rec-pan-frances-step-4', 'rec-pan-frances', 4, 'Servir', 'Espolvorea el azúcar restante y sirve caliente.', null),
  ('rec-yogur-con-manzana-y-avena-step-1', 'rec-yogur-con-manzana-y-avena', 1, 'Picar', 'Lava la manzana y pícala en cubos.', null),
  ('rec-yogur-con-manzana-y-avena-step-2', 'rec-yogur-con-manzana-y-avena', 2, 'Servir', 'Sirve el yogur con la manzana y la avena encima.', null),
  ('rec-omelette-de-verduras-step-1', 'rec-omelette-de-verduras', 1, 'Picar', 'Pica la calabacita, el jitomate y un cuarto de cebolla.', null),
  ('rec-omelette-de-verduras-step-2', 'rec-omelette-de-verduras', 2, 'Sofreír', 'Sofríe las verduras en aceite con sal por 4 minutos.', 240),
  ('rec-omelette-de-verduras-step-3', 'rec-omelette-de-verduras', 3, 'Cuajar', 'Agrega los huevos batidos, tapa y cocina a fuego bajo 5 minutos.', 300),
  ('rec-omelette-de-verduras-step-4', 'rec-omelette-de-verduras', 4, 'Servir', 'Dobla el omelette a la mitad y sirve.', null),
  ('rec-licuado-de-platano-con-avena-step-1', 'rec-licuado-de-platano-con-avena', 1, 'Licuar', 'Licúa la leche con el plátano, la avena y el azúcar hasta que quede sin grumos.', null),
  ('rec-licuado-de-platano-con-avena-step-2', 'rec-licuado-de-platano-con-avena', 2, 'Servir', 'Sirve frío al momento.', null),
  ('rec-tinga-de-pollo-step-1', 'rec-tinga-de-pollo', 1, 'Cocer el pollo', 'Cuece la pechuga en agua con sal y ajo por 25 minutos, deshébrala.', 1500),
  ('rec-tinga-de-pollo-step-2', 'rec-tinga-de-pollo', 2, 'Acitronar', 'Fríe la cebolla en tiras en aceite hasta que esté transparente.', 300),
  ('rec-tinga-de-pollo-step-3', 'rec-tinga-de-pollo', 3, 'Salsa', 'Licúa el jitomate con los chiles y agrégalo a la cebolla. Cocina 10 minutos.', 600),
  ('rec-tinga-de-pollo-step-4', 'rec-tinga-de-pollo', 4, 'Integrar', 'Agrega el pollo, mezcla y sirve en tortillas con crema.', null),
  ('rec-picadillo-step-1', 'rec-picadillo', 1, 'Picar', 'Pela y pica la papa y la zanahoria en cubos pequeños.', null),
  ('rec-picadillo-step-2', 'rec-picadillo', 2, 'Dorar la carne', 'Dora la carne con cebolla y ajo picados, unos 8 minutos.', 480),
  ('rec-picadillo-step-3', 'rec-picadillo', 3, 'Guisar', 'Agrega el jitomate licuado, las verduras y sal. Tapa y cocina 15 minutos.', 900),
  ('rec-picadillo-step-4', 'rec-picadillo', 4, 'Servir', 'Rectifica la sal y sirve con arroz o tortillas.', null),
  ('rec-calabacitas-a-la-mexicana-step-1', 'rec-calabacitas-a-la-mexicana', 1, 'Picar', 'Pica en cubos la calabacita, el jitomate, la cebolla y el chile.', null),
  ('rec-calabacitas-a-la-mexicana-step-2', 'rec-calabacitas-a-la-mexicana', 2, 'Sofreír', 'Sofríe cebolla y chile en aceite 3 minutos.', 180),
  ('rec-calabacitas-a-la-mexicana-step-3', 'rec-calabacitas-a-la-mexicana', 3, 'Cocinar', 'Agrega calabacita, jitomate y sal. Tapa y cocina 12 minutos.', 720),
  ('rec-rajas-con-crema-step-1', 'rec-rajas-con-crema', 1, 'Asar los chiles', 'Asa los chiles en el comal hasta que la piel se queme, unos 10 minutos.', 600),
  ('rec-rajas-con-crema-step-2', 'rec-rajas-con-crema', 2, 'Pelar', 'Mételos en una bolsa 5 minutos, pélalos, quita semillas y córtalos en rajas.', 300),
  ('rec-rajas-con-crema-step-3', 'rec-rajas-con-crema', 3, 'Guisar', 'Sofríe la cebolla, agrega las rajas, la crema y el queso. Cocina 5 minutos.', 300),
  ('rec-rajas-con-crema-step-4', 'rec-rajas-con-crema', 4, 'Servir', 'Sirve con tortillas calientes.', null),
  ('rec-quesadillas-step-1', 'rec-quesadillas', 1, 'Rellenar', 'Deshebra el queso y rellena cada tortilla doblada a la mitad.', null),
  ('rec-quesadillas-step-2', 'rec-quesadillas', 2, 'Calentar', 'Calienta en comal hasta que el queso se derrita, 2 minutos por lado.', 240),
  ('rec-enchiladas-rojas-de-pollo-step-1', 'rec-enchiladas-rojas-de-pollo', 1, 'Cocer el pollo', 'Cuece la pechuga con sal 25 minutos y deshébrala.', 1500),
  ('rec-enchiladas-rojas-de-pollo-step-2', 'rec-enchiladas-rojas-de-pollo', 2, 'Salsa', 'Licúa jitomate, ajo, chiles y un trozo de cebolla. Cocina 10 minutos con sal.', 600),
  ('rec-enchiladas-rojas-de-pollo-step-3', 'rec-enchiladas-rojas-de-pollo', 3, 'Enrollar', 'Pasa las tortillas por aceite, rellénalas de pollo y enróllalas.', null),
  ('rec-enchiladas-rojas-de-pollo-step-4', 'rec-enchiladas-rojas-de-pollo', 4, 'Servir', 'Baña con salsa caliente, crema, queso y cebolla en aros.', null),
  ('rec-burritos-de-frijol-con-queso-step-1', 'rec-burritos-de-frijol-con-queso', 1, 'Cocer los frijoles', 'Cuece los frijoles con sal hasta que estén suaves y macháquelos.', 3600),
  ('rec-burritos-de-frijol-con-queso-step-2', 'rec-burritos-de-frijol-con-queso', 2, 'Armar', 'Calienta las tortillas, úntales frijol, agrega queso y aguacate.', null),
  ('rec-burritos-de-frijol-con-queso-step-3', 'rec-burritos-de-frijol-con-queso', 3, 'Dorar', 'Enróllalos y dóralos en comal 2 minutos por lado.', 240),
  ('rec-arroz-rojo-step-1', 'rec-arroz-rojo', 1, 'Dorar el arroz', 'Fríe el arroz en aceite moviendo seguido hasta que esté dorado, 5 minutos.', 300),
  ('rec-arroz-rojo-step-2', 'rec-arroz-rojo', 2, 'Agregar el caldillo', 'Licúa jitomate, cebolla y ajo con 2 tazas de agua, agrégalo con la zanahoria picada y sal.', null),
  ('rec-arroz-rojo-step-3', 'rec-arroz-rojo', 3, 'Cocer', 'Tapa y cocina a fuego bajo 20 minutos sin destapar.', 1200),
  ('rec-guacamole-con-tostadas-caseras-step-1', 'rec-guacamole-con-tostadas-caseras', 1, 'Tostadas', 'Corta las tortillas en triángulos y hornéalas con un poco de aceite 10 minutos.', 600),
  ('rec-guacamole-con-tostadas-caseras-step-2', 'rec-guacamole-con-tostadas-caseras', 2, 'Machacar', 'Machaca el aguacate con jugo de limón y sal.', null),
  ('rec-guacamole-con-tostadas-caseras-step-3', 'rec-guacamole-con-tostadas-caseras', 3, 'Mezclar', 'Agrega jitomate, cebolla, chile y cilantro picados. Sirve con las tostadas.', null),
  ('rec-sopa-de-fideo-step-1', 'rec-sopa-de-fideo', 1, 'Dorar el fideo', 'Fríe el fideo en aceite moviendo sin parar hasta que esté dorado, 3 minutos.', 180),
  ('rec-sopa-de-fideo-step-2', 'rec-sopa-de-fideo', 2, 'Caldillo', 'Licúa jitomate, cebolla y ajo con un litro de agua y agrégalo al fideo con sal.', null),
  ('rec-sopa-de-fideo-step-3', 'rec-sopa-de-fideo', 3, 'Cocer', 'Cocina a fuego medio 12 minutos, hasta que el fideo esté suave.', 720),
  ('rec-caldo-de-pollo-con-verduras-step-1', 'rec-caldo-de-pollo-con-verduras', 1, 'Hervir el pollo', 'Pon el pollo con cebolla, ajo y sal en 2 litros de agua. Hierve 20 minutos.', 1200),
  ('rec-caldo-de-pollo-con-verduras-step-2', 'rec-caldo-de-pollo-con-verduras', 2, 'Agregar verduras', 'Agrega la papa y la zanahoria en trozos, cocina 10 minutos.', 600),
  ('rec-caldo-de-pollo-con-verduras-step-3', 'rec-caldo-de-pollo-con-verduras', 3, 'Calabacita', 'Agrega la calabacita y cocina 8 minutos más.', 480),
  ('rec-caldo-de-pollo-con-verduras-step-4', 'rec-caldo-de-pollo-con-verduras', 4, 'Servir', 'Sirve con cilantro picado y limón.', null),
  ('rec-lentejas-guisadas-step-1', 'rec-lentejas-guisadas', 1, 'Cocer', 'Cuece las lentejas en 1.5 litros de agua con sal por 25 minutos.', 1500),
  ('rec-lentejas-guisadas-step-2', 'rec-lentejas-guisadas', 2, 'Sofrito', 'Licúa jitomate, cebolla y ajo y fríelo en aceite 5 minutos.', 300),
  ('rec-lentejas-guisadas-step-3', 'rec-lentejas-guisadas', 3, 'Integrar', 'Agrega el sofrito y la zanahoria picada a las lentejas. Cocina 10 minutos.', 600),
  ('rec-sopa-de-codito-step-1', 'rec-sopa-de-codito', 1, 'Dorar la pasta', 'Fríe el codito en aceite hasta que tome color, 3 minutos.', 180),
  ('rec-sopa-de-codito-step-2', 'rec-sopa-de-codito', 2, 'Caldillo', 'Licúa el puré con cebolla, ajo y un litro de agua, agrégalo con sal.', null),
  ('rec-sopa-de-codito-step-3', 'rec-sopa-de-codito', 3, 'Cocer', 'Cocina 12 minutos a fuego medio.', 720),
  ('rec-pollo-a-la-plancha-con-verduras-step-1', 'rec-pollo-a-la-plancha-con-verduras', 1, 'Marinar', 'Sazona el pollo con sal, limón y aceite de oliva.', null),
  ('rec-pollo-a-la-plancha-con-verduras-step-2', 'rec-pollo-a-la-plancha-con-verduras', 2, 'Cocer las verduras', 'Cuece el brócoli y la zanahoria al vapor 8 minutos.', 480),
  ('rec-pollo-a-la-plancha-con-verduras-step-3', 'rec-pollo-a-la-plancha-con-verduras', 3, 'Asar el pollo', 'Asa las pechugas a fuego medio 6 minutos por lado.', 720),
  ('rec-pollo-a-la-plancha-con-verduras-step-4', 'rec-pollo-a-la-plancha-con-verduras', 4, 'Servir', 'Sirve el pollo en rebanadas con las verduras.', null),
  ('rec-ensalada-de-atun-step-1', 'rec-ensalada-de-atun', 1, 'Preparar', 'Lava y corta la lechuga, el jitomate y el aguacate.', null),
  ('rec-ensalada-de-atun-step-2', 'rec-ensalada-de-atun', 2, 'Mezclar', 'Escurre el atún y mézclalo con las verduras, limón, aceite y sal.', null),
  ('rec-ensalada-de-coditos-con-atun-step-1', 'rec-ensalada-de-coditos-con-atun', 1, 'Cocer la pasta', 'Cuece los coditos en agua con sal 10 minutos y escúrrelos.', 600),
  ('rec-ensalada-de-coditos-con-atun-step-2', 'rec-ensalada-de-coditos-con-atun', 2, 'Mezclar', 'Mezcla la pasta fría con el atún, la crema, la zanahoria rallada y sal.', null),
  ('rec-ensalada-de-coditos-con-atun-step-3', 'rec-ensalada-de-coditos-con-atun', 3, 'Enfriar', 'Refrigera 15 minutos antes de servir.', 900),
  ('rec-crema-de-calabacita-step-1', 'rec-crema-de-calabacita', 1, 'Cocer', 'Cuece la calabacita con cebolla y ajo en poca agua 12 minutos.', 720),
  ('rec-crema-de-calabacita-step-2', 'rec-crema-de-calabacita', 2, 'Licuar', 'Licúa las verduras con la leche hasta que quede tersa.', null),
  ('rec-crema-de-calabacita-step-3', 'rec-crema-de-calabacita', 3, 'Terminar', 'Calienta la crema con la mantequilla y sal 5 minutos sin que hierva.', 300),
  ('rec-sandwich-de-atun-step-1', 'rec-sandwich-de-atun', 1, 'Preparar el atún', 'Escurre el atún y mézclalo con jugo de limón y sal.', null),
  ('rec-sandwich-de-atun-step-2', 'rec-sandwich-de-atun', 2, 'Armar', 'Arma los sándwiches con el atún, jitomate y lechuga.', null),
  ('rec-spaghetti-a-la-bolonesa-step-1', 'rec-spaghetti-a-la-bolonesa', 1, 'Cocer la pasta', 'Cuece el spaghetti en agua con sal 10 minutos y escúrrelo.', 600),
  ('rec-spaghetti-a-la-bolonesa-step-2', 'rec-spaghetti-a-la-bolonesa', 2, 'Dorar la carne', 'Sofríe cebolla, ajo y zanahoria picados en aceite, agrega la carne y dora 8 minutos.', 480),
  ('rec-spaghetti-a-la-bolonesa-step-3', 'rec-spaghetti-a-la-bolonesa', 3, 'Salsa', 'Agrega el puré, el orégano y sal. Cocina a fuego bajo 15 minutos.', 900),
  ('rec-spaghetti-a-la-bolonesa-step-4', 'rec-spaghetti-a-la-bolonesa', 4, 'Servir', 'Sirve la pasta con la salsa encima.', null),
  ('rec-pasta-con-verduras-step-1', 'rec-pasta-con-verduras', 1, 'Cocer la pasta', 'Cuece la pasta en agua con sal 10 minutos.', 600),
  ('rec-pasta-con-verduras-step-2', 'rec-pasta-con-verduras', 2, 'Saltear', 'Saltea el ajo y las verduras en tiras en aceite de oliva 6 minutos.', 360),
  ('rec-pasta-con-verduras-step-3', 'rec-pasta-con-verduras', 3, 'Mezclar', 'Mezcla la pasta con las verduras y sirve con queso desmoronado.', null),
  ('rec-arroz-frito-con-verduras-step-1', 'rec-arroz-frito-con-verduras', 1, 'Cocer el arroz', 'Cuece el arroz en agua 18 minutos y déjalo enfriar.', 1080),
  ('rec-arroz-frito-con-verduras-step-2', 'rec-arroz-frito-con-verduras', 2, 'Saltear', 'Saltea la zanahoria y la cebolla picadas en aceite muy caliente 4 minutos.', 240),
  ('rec-arroz-frito-con-verduras-step-3', 'rec-arroz-frito-con-verduras', 3, 'Huevo', 'Haz a un lado las verduras, revuelve los huevos y rómpelos en trozos.', null),
  ('rec-arroz-frito-con-verduras-step-4', 'rec-arroz-frito-con-verduras', 4, 'Terminar', 'Agrega el arroz y la salsa de soya, saltea 3 minutos más.', 180),
  ('rec-pollo-teriyaki-step-1', 'rec-pollo-teriyaki', 1, 'Cocer el arroz', 'Cuece el arroz en agua con sal 18 minutos.', 1080),
  ('rec-pollo-teriyaki-step-2', 'rec-pollo-teriyaki', 2, 'Dorar el pollo', 'Corta el pollo en cubos y dóralo en aceite 8 minutos.', 480),
  ('rec-pollo-teriyaki-step-3', 'rec-pollo-teriyaki', 3, 'Glasear', 'Agrega la soya, el azúcar y el ajo picado, cocina hasta que espese, 4 minutos.', 240),
  ('rec-pollo-teriyaki-step-4', 'rec-pollo-teriyaki', 4, 'Servir', 'Sirve con el arroz y el brócoli cocido al vapor.', null),
  ('rec-tofu-salteado-con-verduras-step-1', 'rec-tofu-salteado-con-verduras', 1, 'Cocer el arroz', 'Cuece el arroz en agua con sal 18 minutos.', 1080),
  ('rec-tofu-salteado-con-verduras-step-2', 'rec-tofu-salteado-con-verduras', 2, 'Dorar el tofu', 'Corta el tofu en cubos y dóralo en aceite 6 minutos.', 360),
  ('rec-tofu-salteado-con-verduras-step-3', 'rec-tofu-salteado-con-verduras', 3, 'Saltear', 'Agrega ajo y verduras en tiras, saltea 5 minutos con la salsa de soya.', 300),
  ('rec-tofu-salteado-con-verduras-step-4', 'rec-tofu-salteado-con-verduras', 4, 'Servir', 'Sirve sobre el arroz.', null),
  ('rec-ensalada-de-garbanzo-step-1', 'rec-ensalada-de-garbanzo', 1, 'Cocer el garbanzo', 'Cuece el garbanzo remojado en agua con sal 60 minutos y escúrrelo.', 3600),
  ('rec-ensalada-de-garbanzo-step-2', 'rec-ensalada-de-garbanzo', 2, 'Picar', 'Pica el jitomate, la cebolla, el pimiento y el cilantro.', null),
  ('rec-ensalada-de-garbanzo-step-3', 'rec-ensalada-de-garbanzo', 3, 'Aderezar', 'Mezcla todo con jugo de limón, aceite de oliva y sal.', null),
  ('rec-pollo-al-horno-con-papas-step-1', 'rec-pollo-al-horno-con-papas', 1, 'Preparar', 'Corta las papas en gajos y ponlas en un refractario con el pollo.', null),
  ('rec-pollo-al-horno-con-papas-step-2', 'rec-pollo-al-horno-con-papas', 2, 'Sazonar', 'Baña con aceite, jugo de limón, ajo picado, orégano y sal.', null),
  ('rec-pollo-al-horno-con-papas-step-3', 'rec-pollo-al-horno-con-papas', 3, 'Hornear', 'Hornea a 200 °C por 40 minutos, hasta que las papas estén doradas.', 2400),
  ('rec-lentejas-con-arroz-step-1', 'rec-lentejas-con-arroz', 1, 'Cocer las lentejas', 'Cuece las lentejas en agua con sal 20 minutos.', 1200),
  ('rec-lentejas-con-arroz-step-2', 'rec-lentejas-con-arroz', 2, 'Agregar el arroz', 'Agrega el arroz y cocina tapado 18 minutos más.', 1080),
  ('rec-lentejas-con-arroz-step-3', 'rec-lentejas-con-arroz', 3, 'Cebolla dorada', 'Fríe la cebolla en tiras en aceite de oliva hasta que esté dorada, 12 minutos, y sirve encima.', 720),
  ('rec-manzana-con-yogur-step-1', 'rec-manzana-con-yogur', 1, 'Cortar', 'Lava la manzana y córtala en rebanadas delgadas.', null),
  ('rec-manzana-con-yogur-step-2', 'rec-manzana-con-yogur', 2, 'Servir', 'Sirve con el yogur endulzado con un poco de azúcar.', null)
on conflict do nothing;

insert into public.recipe_ingredient (id, recipe_id, canonical_product_id, quantity, unit) values
  ('rec-tacos-de-pollo-cp-pechuga-de-pollo', 'rec-tacos-de-pollo', 'cp-pechuga-de-pollo', 500, 'mass_g'),
  ('rec-tacos-de-pollo-cp-tortilla-de-maiz', 'rec-tacos-de-pollo', 'cp-tortilla-de-maiz', 400, 'mass_g'),
  ('rec-tacos-de-pollo-cp-cebolla-blanca', 'rec-tacos-de-pollo', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-tacos-de-pollo-cp-cilantro', 'rec-tacos-de-pollo', 'cp-cilantro', 20, 'mass_g'),
  ('rec-tacos-de-pollo-cp-aceite-vegetal', 'rec-tacos-de-pollo', 'cp-aceite-vegetal', 15, 'volume_ml'),
  ('rec-tacos-de-pollo-cp-sal', 'rec-tacos-de-pollo', 'cp-sal', 2, 'mass_g'),
  ('rec-arroz-con-pollo-cp-pechuga-de-pollo', 'rec-arroz-con-pollo', 'cp-pechuga-de-pollo', 400, 'mass_g'),
  ('rec-arroz-con-pollo-cp-arroz', 'rec-arroz-con-pollo', 'cp-arroz', 300, 'mass_g'),
  ('rec-arroz-con-pollo-cp-jitomate', 'rec-arroz-con-pollo', 'cp-jitomate', 250, 'mass_g'),
  ('rec-arroz-con-pollo-cp-cebolla-blanca', 'rec-arroz-con-pollo', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-arroz-con-pollo-cp-ajo-dientes', 'rec-arroz-con-pollo', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-arroz-con-pollo-cp-aceite-vegetal', 'rec-arroz-con-pollo', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-arroz-con-pollo-cp-sal', 'rec-arroz-con-pollo', 'cp-sal', 3, 'mass_g'),
  ('rec-huevos-a-la-mexicana-cp-huevo', 'rec-huevos-a-la-mexicana', 'cp-huevo', 4, 'unit'),
  ('rec-huevos-a-la-mexicana-cp-jitomate', 'rec-huevos-a-la-mexicana', 'cp-jitomate', 150, 'mass_g'),
  ('rec-huevos-a-la-mexicana-cp-cebolla-blanca', 'rec-huevos-a-la-mexicana', 'cp-cebolla-blanca', 0.5, 'unit'),
  ('rec-huevos-a-la-mexicana-cp-chile-serrano', 'rec-huevos-a-la-mexicana', 'cp-chile-serrano', 1, 'unit'),
  ('rec-huevos-a-la-mexicana-cp-aceite-vegetal', 'rec-huevos-a-la-mexicana', 'cp-aceite-vegetal', 10, 'volume_ml'),
  ('rec-huevos-a-la-mexicana-cp-sal', 'rec-huevos-a-la-mexicana', 'cp-sal', 1, 'mass_g'),
  ('rec-spaghetti-con-jitomate-cp-pasta-spaghetti', 'rec-spaghetti-con-jitomate', 'cp-pasta-spaghetti', 400, 'mass_g'),
  ('rec-spaghetti-con-jitomate-cp-jitomate', 'rec-spaghetti-con-jitomate', 'cp-jitomate', 500, 'mass_g'),
  ('rec-spaghetti-con-jitomate-cp-ajo-dientes', 'rec-spaghetti-con-jitomate', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-spaghetti-con-jitomate-cp-aceite-vegetal', 'rec-spaghetti-con-jitomate', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-spaghetti-con-jitomate-cp-sal', 'rec-spaghetti-con-jitomate', 'cp-sal', 3, 'mass_g'),
  ('rec-spaghetti-con-jitomate-cp-queso-fresco', 'rec-spaghetti-con-jitomate', 'cp-queso-fresco', 100, 'mass_g'),
  ('rec-enfrijoladas-cp-frijol-pinto', 'rec-enfrijoladas', 'cp-frijol-pinto', 300, 'mass_g'),
  ('rec-enfrijoladas-cp-tortilla-de-maiz', 'rec-enfrijoladas', 'cp-tortilla-de-maiz', 400, 'mass_g'),
  ('rec-enfrijoladas-cp-queso-fresco', 'rec-enfrijoladas', 'cp-queso-fresco', 150, 'mass_g'),
  ('rec-enfrijoladas-cp-crema', 'rec-enfrijoladas', 'cp-crema', 100, 'volume_ml'),
  ('rec-enfrijoladas-cp-cebolla-blanca', 'rec-enfrijoladas', 'cp-cebolla-blanca', 0.5, 'unit'),
  ('rec-enfrijoladas-cp-aceite-vegetal', 'rec-enfrijoladas', 'cp-aceite-vegetal', 20, 'volume_ml'),
  ('rec-enfrijoladas-cp-sal', 'rec-enfrijoladas', 'cp-sal', 3, 'mass_g'),
  ('rec-avena-con-platano-cp-avena', 'rec-avena-con-platano', 'cp-avena', 100, 'mass_g'),
  ('rec-avena-con-platano-cp-leche-entera', 'rec-avena-con-platano', 'cp-leche-entera', 500, 'volume_ml'),
  ('rec-avena-con-platano-cp-platano', 'rec-avena-con-platano', 'cp-platano', 2, 'unit'),
  ('rec-chilaquiles-rojos-cp-tortilla-de-maiz', 'rec-chilaquiles-rojos', 'cp-tortilla-de-maiz', 400, 'mass_g'),
  ('rec-chilaquiles-rojos-cp-jitomate', 'rec-chilaquiles-rojos', 'cp-jitomate', 500, 'mass_g'),
  ('rec-chilaquiles-rojos-cp-cebolla-blanca', 'rec-chilaquiles-rojos', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-chilaquiles-rojos-cp-ajo-dientes', 'rec-chilaquiles-rojos', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-chilaquiles-rojos-cp-chile-serrano', 'rec-chilaquiles-rojos', 'cp-chile-serrano', 2, 'unit'),
  ('rec-chilaquiles-rojos-cp-crema', 'rec-chilaquiles-rojos', 'cp-crema', 60, 'volume_ml'),
  ('rec-chilaquiles-rojos-cp-queso-fresco', 'rec-chilaquiles-rojos', 'cp-queso-fresco', 100, 'mass_g'),
  ('rec-chilaquiles-rojos-cp-aceite-vegetal', 'rec-chilaquiles-rojos', 'cp-aceite-vegetal', 45, 'volume_ml'),
  ('rec-chilaquiles-rojos-cp-sal', 'rec-chilaquiles-rojos', 'cp-sal', 2, 'mass_g'),
  ('rec-molletes-con-pico-de-gallo-cp-bolillo', 'rec-molletes-con-pico-de-gallo', 'cp-bolillo', 4, 'unit'),
  ('rec-molletes-con-pico-de-gallo-cp-frijol-pinto', 'rec-molletes-con-pico-de-gallo', 'cp-frijol-pinto', 250, 'mass_g'),
  ('rec-molletes-con-pico-de-gallo-cp-queso-oaxaca', 'rec-molletes-con-pico-de-gallo', 'cp-queso-oaxaca', 200, 'mass_g'),
  ('rec-molletes-con-pico-de-gallo-cp-jitomate', 'rec-molletes-con-pico-de-gallo', 'cp-jitomate', 200, 'mass_g'),
  ('rec-molletes-con-pico-de-gallo-cp-cebolla-blanca', 'rec-molletes-con-pico-de-gallo', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-molletes-con-pico-de-gallo-cp-cilantro', 'rec-molletes-con-pico-de-gallo', 'cp-cilantro', 10, 'mass_g'),
  ('rec-molletes-con-pico-de-gallo-cp-chile-serrano', 'rec-molletes-con-pico-de-gallo', 'cp-chile-serrano', 1, 'unit'),
  ('rec-molletes-con-pico-de-gallo-cp-sal', 'rec-molletes-con-pico-de-gallo', 'cp-sal', 2, 'mass_g'),
  ('rec-huevos-rancheros-cp-huevo', 'rec-huevos-rancheros', 'cp-huevo', 4, 'unit'),
  ('rec-huevos-rancheros-cp-tortilla-de-maiz', 'rec-huevos-rancheros', 'cp-tortilla-de-maiz', 120, 'mass_g'),
  ('rec-huevos-rancheros-cp-jitomate', 'rec-huevos-rancheros', 'cp-jitomate', 300, 'mass_g'),
  ('rec-huevos-rancheros-cp-cebolla-blanca', 'rec-huevos-rancheros', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-huevos-rancheros-cp-ajo-dientes', 'rec-huevos-rancheros', 'cp-ajo-dientes', 1, 'unit'),
  ('rec-huevos-rancheros-cp-chile-serrano', 'rec-huevos-rancheros', 'cp-chile-serrano', 1, 'unit'),
  ('rec-huevos-rancheros-cp-aceite-vegetal', 'rec-huevos-rancheros', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-huevos-rancheros-cp-sal', 'rec-huevos-rancheros', 'cp-sal', 2, 'mass_g'),
  ('rec-pan-frances-cp-pan-de-caja', 'rec-pan-frances', 'cp-pan-de-caja', 320, 'mass_g'),
  ('rec-pan-frances-cp-huevo', 'rec-pan-frances', 'cp-huevo', 3, 'unit'),
  ('rec-pan-frances-cp-leche-entera', 'rec-pan-frances', 'cp-leche-entera', 240, 'volume_ml'),
  ('rec-pan-frances-cp-mantequilla', 'rec-pan-frances', 'cp-mantequilla', 30, 'mass_g'),
  ('rec-pan-frances-cp-azucar', 'rec-pan-frances', 'cp-azucar', 30, 'mass_g'),
  ('rec-yogur-con-manzana-y-avena-cp-yogur-natural', 'rec-yogur-con-manzana-y-avena', 'cp-yogur-natural', 300, 'mass_g'),
  ('rec-yogur-con-manzana-y-avena-cp-manzana', 'rec-yogur-con-manzana-y-avena', 'cp-manzana', 1, 'unit'),
  ('rec-yogur-con-manzana-y-avena-cp-avena', 'rec-yogur-con-manzana-y-avena', 'cp-avena', 60, 'mass_g'),
  ('rec-omelette-de-verduras-cp-huevo', 'rec-omelette-de-verduras', 'cp-huevo', 4, 'unit'),
  ('rec-omelette-de-verduras-cp-calabacita', 'rec-omelette-de-verduras', 'cp-calabacita', 150, 'mass_g'),
  ('rec-omelette-de-verduras-cp-jitomate', 'rec-omelette-de-verduras', 'cp-jitomate', 100, 'mass_g'),
  ('rec-omelette-de-verduras-cp-cebolla-blanca', 'rec-omelette-de-verduras', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-omelette-de-verduras-cp-aceite-vegetal', 'rec-omelette-de-verduras', 'cp-aceite-vegetal', 15, 'volume_ml'),
  ('rec-omelette-de-verduras-cp-sal', 'rec-omelette-de-verduras', 'cp-sal', 2, 'mass_g'),
  ('rec-licuado-de-platano-con-avena-cp-leche-entera', 'rec-licuado-de-platano-con-avena', 'cp-leche-entera', 480, 'volume_ml'),
  ('rec-licuado-de-platano-con-avena-cp-platano', 'rec-licuado-de-platano-con-avena', 'cp-platano', 2, 'unit'),
  ('rec-licuado-de-platano-con-avena-cp-avena', 'rec-licuado-de-platano-con-avena', 'cp-avena', 40, 'mass_g'),
  ('rec-licuado-de-platano-con-avena-cp-azucar', 'rec-licuado-de-platano-con-avena', 'cp-azucar', 10, 'mass_g'),
  ('rec-tinga-de-pollo-cp-pechuga-de-pollo', 'rec-tinga-de-pollo', 'cp-pechuga-de-pollo', 600, 'mass_g'),
  ('rec-tinga-de-pollo-cp-jitomate', 'rec-tinga-de-pollo', 'cp-jitomate', 500, 'mass_g'),
  ('rec-tinga-de-pollo-cp-cebolla-blanca', 'rec-tinga-de-pollo', 'cp-cebolla-blanca', 2, 'unit'),
  ('rec-tinga-de-pollo-cp-ajo-dientes', 'rec-tinga-de-pollo', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-tinga-de-pollo-cp-chile-serrano', 'rec-tinga-de-pollo', 'cp-chile-serrano', 2, 'unit'),
  ('rec-tinga-de-pollo-cp-tortilla-de-maiz', 'rec-tinga-de-pollo', 'cp-tortilla-de-maiz', 400, 'mass_g'),
  ('rec-tinga-de-pollo-cp-crema', 'rec-tinga-de-pollo', 'cp-crema', 60, 'volume_ml'),
  ('rec-tinga-de-pollo-cp-aceite-vegetal', 'rec-tinga-de-pollo', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-tinga-de-pollo-cp-sal', 'rec-tinga-de-pollo', 'cp-sal', 2, 'mass_g'),
  ('rec-picadillo-cp-carne-molida-de-res', 'rec-picadillo', 'cp-carne-molida-de-res', 500, 'mass_g'),
  ('rec-picadillo-cp-papa', 'rec-picadillo', 'cp-papa', 300, 'mass_g'),
  ('rec-picadillo-cp-zanahoria', 'rec-picadillo', 'cp-zanahoria', 200, 'mass_g'),
  ('rec-picadillo-cp-jitomate', 'rec-picadillo', 'cp-jitomate', 400, 'mass_g'),
  ('rec-picadillo-cp-cebolla-blanca', 'rec-picadillo', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-picadillo-cp-ajo-dientes', 'rec-picadillo', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-picadillo-cp-aceite-vegetal', 'rec-picadillo', 'cp-aceite-vegetal', 15, 'volume_ml'),
  ('rec-picadillo-cp-sal', 'rec-picadillo', 'cp-sal', 2, 'mass_g'),
  ('rec-calabacitas-a-la-mexicana-cp-calabacita', 'rec-calabacitas-a-la-mexicana', 'cp-calabacita', 700, 'mass_g'),
  ('rec-calabacitas-a-la-mexicana-cp-jitomate', 'rec-calabacitas-a-la-mexicana', 'cp-jitomate', 300, 'mass_g'),
  ('rec-calabacitas-a-la-mexicana-cp-cebolla-blanca', 'rec-calabacitas-a-la-mexicana', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-calabacitas-a-la-mexicana-cp-chile-serrano', 'rec-calabacitas-a-la-mexicana', 'cp-chile-serrano', 1, 'unit'),
  ('rec-calabacitas-a-la-mexicana-cp-aceite-vegetal', 'rec-calabacitas-a-la-mexicana', 'cp-aceite-vegetal', 15, 'volume_ml'),
  ('rec-calabacitas-a-la-mexicana-cp-sal', 'rec-calabacitas-a-la-mexicana', 'cp-sal', 2, 'mass_g'),
  ('rec-rajas-con-crema-cp-chile-poblano', 'rec-rajas-con-crema', 'cp-chile-poblano', 4, 'unit'),
  ('rec-rajas-con-crema-cp-cebolla-blanca', 'rec-rajas-con-crema', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-rajas-con-crema-cp-crema', 'rec-rajas-con-crema', 'cp-crema', 240, 'volume_ml'),
  ('rec-rajas-con-crema-cp-queso-oaxaca', 'rec-rajas-con-crema', 'cp-queso-oaxaca', 150, 'mass_g'),
  ('rec-rajas-con-crema-cp-tortilla-de-maiz', 'rec-rajas-con-crema', 'cp-tortilla-de-maiz', 400, 'mass_g'),
  ('rec-rajas-con-crema-cp-aceite-vegetal', 'rec-rajas-con-crema', 'cp-aceite-vegetal', 15, 'volume_ml'),
  ('rec-rajas-con-crema-cp-sal', 'rec-rajas-con-crema', 'cp-sal', 2, 'mass_g'),
  ('rec-quesadillas-cp-tortilla-de-maiz', 'rec-quesadillas', 'cp-tortilla-de-maiz', 400, 'mass_g'),
  ('rec-quesadillas-cp-queso-oaxaca', 'rec-quesadillas', 'cp-queso-oaxaca', 250, 'mass_g'),
  ('rec-enchiladas-rojas-de-pollo-cp-pechuga-de-pollo', 'rec-enchiladas-rojas-de-pollo', 'cp-pechuga-de-pollo', 400, 'mass_g'),
  ('rec-enchiladas-rojas-de-pollo-cp-tortilla-de-maiz', 'rec-enchiladas-rojas-de-pollo', 'cp-tortilla-de-maiz', 400, 'mass_g'),
  ('rec-enchiladas-rojas-de-pollo-cp-jitomate', 'rec-enchiladas-rojas-de-pollo', 'cp-jitomate', 500, 'mass_g'),
  ('rec-enchiladas-rojas-de-pollo-cp-ajo-dientes', 'rec-enchiladas-rojas-de-pollo', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-enchiladas-rojas-de-pollo-cp-cebolla-blanca', 'rec-enchiladas-rojas-de-pollo', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-enchiladas-rojas-de-pollo-cp-chile-serrano', 'rec-enchiladas-rojas-de-pollo', 'cp-chile-serrano', 2, 'unit'),
  ('rec-enchiladas-rojas-de-pollo-cp-crema', 'rec-enchiladas-rojas-de-pollo', 'cp-crema', 60, 'volume_ml'),
  ('rec-enchiladas-rojas-de-pollo-cp-queso-fresco', 'rec-enchiladas-rojas-de-pollo', 'cp-queso-fresco', 100, 'mass_g'),
  ('rec-enchiladas-rojas-de-pollo-cp-aceite-vegetal', 'rec-enchiladas-rojas-de-pollo', 'cp-aceite-vegetal', 45, 'volume_ml'),
  ('rec-enchiladas-rojas-de-pollo-cp-sal', 'rec-enchiladas-rojas-de-pollo', 'cp-sal', 2, 'mass_g'),
  ('rec-burritos-de-frijol-con-queso-cp-tortilla-de-harina', 'rec-burritos-de-frijol-con-queso', 'cp-tortilla-de-harina', 400, 'mass_g'),
  ('rec-burritos-de-frijol-con-queso-cp-frijol-pinto', 'rec-burritos-de-frijol-con-queso', 'cp-frijol-pinto', 300, 'mass_g'),
  ('rec-burritos-de-frijol-con-queso-cp-queso-oaxaca', 'rec-burritos-de-frijol-con-queso', 'cp-queso-oaxaca', 200, 'mass_g'),
  ('rec-burritos-de-frijol-con-queso-cp-aguacate', 'rec-burritos-de-frijol-con-queso', 'cp-aguacate', 1, 'unit'),
  ('rec-burritos-de-frijol-con-queso-cp-sal', 'rec-burritos-de-frijol-con-queso', 'cp-sal', 2, 'mass_g'),
  ('rec-arroz-rojo-cp-arroz', 'rec-arroz-rojo', 'cp-arroz', 250, 'mass_g'),
  ('rec-arroz-rojo-cp-jitomate', 'rec-arroz-rojo', 'cp-jitomate', 250, 'mass_g'),
  ('rec-arroz-rojo-cp-cebolla-blanca', 'rec-arroz-rojo', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-arroz-rojo-cp-ajo-dientes', 'rec-arroz-rojo', 'cp-ajo-dientes', 1, 'unit'),
  ('rec-arroz-rojo-cp-zanahoria', 'rec-arroz-rojo', 'cp-zanahoria', 100, 'mass_g'),
  ('rec-arroz-rojo-cp-aceite-vegetal', 'rec-arroz-rojo', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-arroz-rojo-cp-sal', 'rec-arroz-rojo', 'cp-sal', 2, 'mass_g'),
  ('rec-guacamole-con-tostadas-caseras-cp-aguacate', 'rec-guacamole-con-tostadas-caseras', 'cp-aguacate', 3, 'unit'),
  ('rec-guacamole-con-tostadas-caseras-cp-jitomate', 'rec-guacamole-con-tostadas-caseras', 'cp-jitomate', 150, 'mass_g'),
  ('rec-guacamole-con-tostadas-caseras-cp-cebolla-blanca', 'rec-guacamole-con-tostadas-caseras', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-guacamole-con-tostadas-caseras-cp-chile-serrano', 'rec-guacamole-con-tostadas-caseras', 'cp-chile-serrano', 1, 'unit'),
  ('rec-guacamole-con-tostadas-caseras-cp-cilantro', 'rec-guacamole-con-tostadas-caseras', 'cp-cilantro', 10, 'mass_g'),
  ('rec-guacamole-con-tostadas-caseras-cp-limon', 'rec-guacamole-con-tostadas-caseras', 'cp-limon', 1, 'unit'),
  ('rec-guacamole-con-tostadas-caseras-cp-tortilla-de-maiz', 'rec-guacamole-con-tostadas-caseras', 'cp-tortilla-de-maiz', 200, 'mass_g'),
  ('rec-guacamole-con-tostadas-caseras-cp-aceite-vegetal', 'rec-guacamole-con-tostadas-caseras', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-guacamole-con-tostadas-caseras-cp-sal', 'rec-guacamole-con-tostadas-caseras', 'cp-sal', 2, 'mass_g'),
  ('rec-sopa-de-fideo-cp-fideo', 'rec-sopa-de-fideo', 'cp-fideo', 200, 'mass_g'),
  ('rec-sopa-de-fideo-cp-jitomate', 'rec-sopa-de-fideo', 'cp-jitomate', 300, 'mass_g'),
  ('rec-sopa-de-fideo-cp-cebolla-blanca', 'rec-sopa-de-fideo', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-sopa-de-fideo-cp-ajo-dientes', 'rec-sopa-de-fideo', 'cp-ajo-dientes', 1, 'unit'),
  ('rec-sopa-de-fideo-cp-aceite-vegetal', 'rec-sopa-de-fideo', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-sopa-de-fideo-cp-sal', 'rec-sopa-de-fideo', 'cp-sal', 2, 'mass_g'),
  ('rec-caldo-de-pollo-con-verduras-cp-pechuga-de-pollo', 'rec-caldo-de-pollo-con-verduras', 'cp-pechuga-de-pollo', 500, 'mass_g'),
  ('rec-caldo-de-pollo-con-verduras-cp-papa', 'rec-caldo-de-pollo-con-verduras', 'cp-papa', 300, 'mass_g'),
  ('rec-caldo-de-pollo-con-verduras-cp-zanahoria', 'rec-caldo-de-pollo-con-verduras', 'cp-zanahoria', 200, 'mass_g'),
  ('rec-caldo-de-pollo-con-verduras-cp-calabacita', 'rec-caldo-de-pollo-con-verduras', 'cp-calabacita', 200, 'mass_g'),
  ('rec-caldo-de-pollo-con-verduras-cp-cebolla-blanca', 'rec-caldo-de-pollo-con-verduras', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-caldo-de-pollo-con-verduras-cp-ajo-dientes', 'rec-caldo-de-pollo-con-verduras', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-caldo-de-pollo-con-verduras-cp-cilantro', 'rec-caldo-de-pollo-con-verduras', 'cp-cilantro', 10, 'mass_g'),
  ('rec-caldo-de-pollo-con-verduras-cp-limon', 'rec-caldo-de-pollo-con-verduras', 'cp-limon', 2, 'unit'),
  ('rec-caldo-de-pollo-con-verduras-cp-sal', 'rec-caldo-de-pollo-con-verduras', 'cp-sal', 2, 'mass_g'),
  ('rec-lentejas-guisadas-cp-lentejas', 'rec-lentejas-guisadas', 'cp-lentejas', 300, 'mass_g'),
  ('rec-lentejas-guisadas-cp-jitomate', 'rec-lentejas-guisadas', 'cp-jitomate', 250, 'mass_g'),
  ('rec-lentejas-guisadas-cp-cebolla-blanca', 'rec-lentejas-guisadas', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-lentejas-guisadas-cp-ajo-dientes', 'rec-lentejas-guisadas', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-lentejas-guisadas-cp-zanahoria', 'rec-lentejas-guisadas', 'cp-zanahoria', 150, 'mass_g'),
  ('rec-lentejas-guisadas-cp-aceite-vegetal', 'rec-lentejas-guisadas', 'cp-aceite-vegetal', 15, 'volume_ml'),
  ('rec-lentejas-guisadas-cp-sal', 'rec-lentejas-guisadas', 'cp-sal', 2, 'mass_g'),
  ('rec-sopa-de-codito-cp-pasta-de-codo', 'rec-sopa-de-codito', 'cp-pasta-de-codo', 200, 'mass_g'),
  ('rec-sopa-de-codito-cp-pure-de-tomate', 'rec-sopa-de-codito', 'cp-pure-de-tomate', 210, 'mass_g'),
  ('rec-sopa-de-codito-cp-cebolla-blanca', 'rec-sopa-de-codito', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-sopa-de-codito-cp-ajo-dientes', 'rec-sopa-de-codito', 'cp-ajo-dientes', 1, 'unit'),
  ('rec-sopa-de-codito-cp-aceite-vegetal', 'rec-sopa-de-codito', 'cp-aceite-vegetal', 15, 'volume_ml'),
  ('rec-sopa-de-codito-cp-sal', 'rec-sopa-de-codito', 'cp-sal', 2, 'mass_g'),
  ('rec-pollo-a-la-plancha-con-verduras-cp-pechuga-de-pollo', 'rec-pollo-a-la-plancha-con-verduras', 'cp-pechuga-de-pollo', 600, 'mass_g'),
  ('rec-pollo-a-la-plancha-con-verduras-cp-brocoli', 'rec-pollo-a-la-plancha-con-verduras', 'cp-brocoli', 300, 'mass_g'),
  ('rec-pollo-a-la-plancha-con-verduras-cp-zanahoria', 'rec-pollo-a-la-plancha-con-verduras', 'cp-zanahoria', 200, 'mass_g'),
  ('rec-pollo-a-la-plancha-con-verduras-cp-aceite-de-oliva', 'rec-pollo-a-la-plancha-con-verduras', 'cp-aceite-de-oliva', 30, 'volume_ml'),
  ('rec-pollo-a-la-plancha-con-verduras-cp-limon', 'rec-pollo-a-la-plancha-con-verduras', 'cp-limon', 2, 'unit'),
  ('rec-pollo-a-la-plancha-con-verduras-cp-sal', 'rec-pollo-a-la-plancha-con-verduras', 'cp-sal', 2, 'mass_g'),
  ('rec-ensalada-de-atun-cp-atun-en-agua', 'rec-ensalada-de-atun', 'cp-atun-en-agua', 280, 'mass_g'),
  ('rec-ensalada-de-atun-cp-lechuga', 'rec-ensalada-de-atun', 'cp-lechuga', 1, 'unit'),
  ('rec-ensalada-de-atun-cp-jitomate', 'rec-ensalada-de-atun', 'cp-jitomate', 200, 'mass_g'),
  ('rec-ensalada-de-atun-cp-aguacate', 'rec-ensalada-de-atun', 'cp-aguacate', 1, 'unit'),
  ('rec-ensalada-de-atun-cp-limon', 'rec-ensalada-de-atun', 'cp-limon', 1, 'unit'),
  ('rec-ensalada-de-atun-cp-aceite-de-oliva', 'rec-ensalada-de-atun', 'cp-aceite-de-oliva', 15, 'volume_ml'),
  ('rec-ensalada-de-atun-cp-sal', 'rec-ensalada-de-atun', 'cp-sal', 2, 'mass_g'),
  ('rec-ensalada-de-coditos-con-atun-cp-pasta-de-codo', 'rec-ensalada-de-coditos-con-atun', 'cp-pasta-de-codo', 200, 'mass_g'),
  ('rec-ensalada-de-coditos-con-atun-cp-atun-en-agua', 'rec-ensalada-de-coditos-con-atun', 'cp-atun-en-agua', 280, 'mass_g'),
  ('rec-ensalada-de-coditos-con-atun-cp-crema', 'rec-ensalada-de-coditos-con-atun', 'cp-crema', 60, 'volume_ml'),
  ('rec-ensalada-de-coditos-con-atun-cp-zanahoria', 'rec-ensalada-de-coditos-con-atun', 'cp-zanahoria', 100, 'mass_g'),
  ('rec-ensalada-de-coditos-con-atun-cp-sal', 'rec-ensalada-de-coditos-con-atun', 'cp-sal', 2, 'mass_g'),
  ('rec-crema-de-calabacita-cp-calabacita', 'rec-crema-de-calabacita', 'cp-calabacita', 600, 'mass_g'),
  ('rec-crema-de-calabacita-cp-cebolla-blanca', 'rec-crema-de-calabacita', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-crema-de-calabacita-cp-ajo-dientes', 'rec-crema-de-calabacita', 'cp-ajo-dientes', 1, 'unit'),
  ('rec-crema-de-calabacita-cp-leche-entera', 'rec-crema-de-calabacita', 'cp-leche-entera', 480, 'volume_ml'),
  ('rec-crema-de-calabacita-cp-mantequilla', 'rec-crema-de-calabacita', 'cp-mantequilla', 20, 'mass_g'),
  ('rec-crema-de-calabacita-cp-sal', 'rec-crema-de-calabacita', 'cp-sal', 2, 'mass_g'),
  ('rec-sandwich-de-atun-cp-pan-de-caja', 'rec-sandwich-de-atun', 'cp-pan-de-caja', 160, 'mass_g'),
  ('rec-sandwich-de-atun-cp-atun-en-agua', 'rec-sandwich-de-atun', 'cp-atun-en-agua', 140, 'mass_g'),
  ('rec-sandwich-de-atun-cp-jitomate', 'rec-sandwich-de-atun', 'cp-jitomate', 100, 'mass_g'),
  ('rec-sandwich-de-atun-cp-lechuga', 'rec-sandwich-de-atun', 'cp-lechuga', 1, 'unit'),
  ('rec-sandwich-de-atun-cp-limon', 'rec-sandwich-de-atun', 'cp-limon', 1, 'unit'),
  ('rec-sandwich-de-atun-cp-sal', 'rec-sandwich-de-atun', 'cp-sal', 2, 'mass_g'),
  ('rec-spaghetti-a-la-bolonesa-cp-pasta-spaghetti', 'rec-spaghetti-a-la-bolonesa', 'cp-pasta-spaghetti', 400, 'mass_g'),
  ('rec-spaghetti-a-la-bolonesa-cp-carne-molida-de-res', 'rec-spaghetti-a-la-bolonesa', 'cp-carne-molida-de-res', 400, 'mass_g'),
  ('rec-spaghetti-a-la-bolonesa-cp-pure-de-tomate', 'rec-spaghetti-a-la-bolonesa', 'cp-pure-de-tomate', 420, 'mass_g'),
  ('rec-spaghetti-a-la-bolonesa-cp-cebolla-blanca', 'rec-spaghetti-a-la-bolonesa', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-spaghetti-a-la-bolonesa-cp-ajo-dientes', 'rec-spaghetti-a-la-bolonesa', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-spaghetti-a-la-bolonesa-cp-zanahoria', 'rec-spaghetti-a-la-bolonesa', 'cp-zanahoria', 100, 'mass_g'),
  ('rec-spaghetti-a-la-bolonesa-cp-aceite-de-oliva', 'rec-spaghetti-a-la-bolonesa', 'cp-aceite-de-oliva', 30, 'volume_ml'),
  ('rec-spaghetti-a-la-bolonesa-cp-oregano', 'rec-spaghetti-a-la-bolonesa', 'cp-oregano', 2, 'mass_g'),
  ('rec-spaghetti-a-la-bolonesa-cp-sal', 'rec-spaghetti-a-la-bolonesa', 'cp-sal', 2, 'mass_g'),
  ('rec-pasta-con-verduras-cp-pasta-spaghetti', 'rec-pasta-con-verduras', 'cp-pasta-spaghetti', 400, 'mass_g'),
  ('rec-pasta-con-verduras-cp-calabacita', 'rec-pasta-con-verduras', 'cp-calabacita', 300, 'mass_g'),
  ('rec-pasta-con-verduras-cp-pimiento-morron', 'rec-pasta-con-verduras', 'cp-pimiento-morron', 1, 'unit'),
  ('rec-pasta-con-verduras-cp-brocoli', 'rec-pasta-con-verduras', 'cp-brocoli', 200, 'mass_g'),
  ('rec-pasta-con-verduras-cp-ajo-dientes', 'rec-pasta-con-verduras', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-pasta-con-verduras-cp-aceite-de-oliva', 'rec-pasta-con-verduras', 'cp-aceite-de-oliva', 45, 'volume_ml'),
  ('rec-pasta-con-verduras-cp-queso-fresco', 'rec-pasta-con-verduras', 'cp-queso-fresco', 100, 'mass_g'),
  ('rec-pasta-con-verduras-cp-sal', 'rec-pasta-con-verduras', 'cp-sal', 2, 'mass_g'),
  ('rec-arroz-frito-con-verduras-cp-arroz', 'rec-arroz-frito-con-verduras', 'cp-arroz', 300, 'mass_g'),
  ('rec-arroz-frito-con-verduras-cp-huevo', 'rec-arroz-frito-con-verduras', 'cp-huevo', 2, 'unit'),
  ('rec-arroz-frito-con-verduras-cp-zanahoria', 'rec-arroz-frito-con-verduras', 'cp-zanahoria', 150, 'mass_g'),
  ('rec-arroz-frito-con-verduras-cp-cebolla-blanca', 'rec-arroz-frito-con-verduras', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-arroz-frito-con-verduras-cp-salsa-de-soya', 'rec-arroz-frito-con-verduras', 'cp-salsa-de-soya', 45, 'volume_ml'),
  ('rec-arroz-frito-con-verduras-cp-aceite-vegetal', 'rec-arroz-frito-con-verduras', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-pollo-teriyaki-cp-pechuga-de-pollo', 'rec-pollo-teriyaki', 'cp-pechuga-de-pollo', 600, 'mass_g'),
  ('rec-pollo-teriyaki-cp-salsa-de-soya', 'rec-pollo-teriyaki', 'cp-salsa-de-soya', 60, 'volume_ml'),
  ('rec-pollo-teriyaki-cp-azucar', 'rec-pollo-teriyaki', 'cp-azucar', 30, 'mass_g'),
  ('rec-pollo-teriyaki-cp-ajo-dientes', 'rec-pollo-teriyaki', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-pollo-teriyaki-cp-arroz', 'rec-pollo-teriyaki', 'cp-arroz', 250, 'mass_g'),
  ('rec-pollo-teriyaki-cp-brocoli', 'rec-pollo-teriyaki', 'cp-brocoli', 300, 'mass_g'),
  ('rec-pollo-teriyaki-cp-aceite-vegetal', 'rec-pollo-teriyaki', 'cp-aceite-vegetal', 15, 'volume_ml'),
  ('rec-tofu-salteado-con-verduras-cp-tofu-firme', 'rec-tofu-salteado-con-verduras', 'cp-tofu-firme', 400, 'mass_g'),
  ('rec-tofu-salteado-con-verduras-cp-brocoli', 'rec-tofu-salteado-con-verduras', 'cp-brocoli', 250, 'mass_g'),
  ('rec-tofu-salteado-con-verduras-cp-pimiento-morron', 'rec-tofu-salteado-con-verduras', 'cp-pimiento-morron', 1, 'unit'),
  ('rec-tofu-salteado-con-verduras-cp-zanahoria', 'rec-tofu-salteado-con-verduras', 'cp-zanahoria', 150, 'mass_g'),
  ('rec-tofu-salteado-con-verduras-cp-salsa-de-soya', 'rec-tofu-salteado-con-verduras', 'cp-salsa-de-soya', 45, 'volume_ml'),
  ('rec-tofu-salteado-con-verduras-cp-ajo-dientes', 'rec-tofu-salteado-con-verduras', 'cp-ajo-dientes', 2, 'unit'),
  ('rec-tofu-salteado-con-verduras-cp-arroz', 'rec-tofu-salteado-con-verduras', 'cp-arroz', 250, 'mass_g'),
  ('rec-tofu-salteado-con-verduras-cp-aceite-vegetal', 'rec-tofu-salteado-con-verduras', 'cp-aceite-vegetal', 30, 'volume_ml'),
  ('rec-ensalada-de-garbanzo-cp-garbanzo', 'rec-ensalada-de-garbanzo', 'cp-garbanzo', 250, 'mass_g'),
  ('rec-ensalada-de-garbanzo-cp-jitomate', 'rec-ensalada-de-garbanzo', 'cp-jitomate', 250, 'mass_g'),
  ('rec-ensalada-de-garbanzo-cp-cebolla-blanca', 'rec-ensalada-de-garbanzo', 'cp-cebolla-blanca', 1, 'unit'),
  ('rec-ensalada-de-garbanzo-cp-pimiento-morron', 'rec-ensalada-de-garbanzo', 'cp-pimiento-morron', 1, 'unit'),
  ('rec-ensalada-de-garbanzo-cp-limon', 'rec-ensalada-de-garbanzo', 'cp-limon', 2, 'unit'),
  ('rec-ensalada-de-garbanzo-cp-aceite-de-oliva', 'rec-ensalada-de-garbanzo', 'cp-aceite-de-oliva', 45, 'volume_ml'),
  ('rec-ensalada-de-garbanzo-cp-cilantro', 'rec-ensalada-de-garbanzo', 'cp-cilantro', 10, 'mass_g'),
  ('rec-ensalada-de-garbanzo-cp-sal', 'rec-ensalada-de-garbanzo', 'cp-sal', 2, 'mass_g'),
  ('rec-pollo-al-horno-con-papas-cp-pechuga-de-pollo', 'rec-pollo-al-horno-con-papas', 'cp-pechuga-de-pollo', 700, 'mass_g'),
  ('rec-pollo-al-horno-con-papas-cp-papa', 'rec-pollo-al-horno-con-papas', 'cp-papa', 600, 'mass_g'),
  ('rec-pollo-al-horno-con-papas-cp-ajo-dientes', 'rec-pollo-al-horno-con-papas', 'cp-ajo-dientes', 3, 'unit'),
  ('rec-pollo-al-horno-con-papas-cp-aceite-de-oliva', 'rec-pollo-al-horno-con-papas', 'cp-aceite-de-oliva', 45, 'volume_ml'),
  ('rec-pollo-al-horno-con-papas-cp-oregano', 'rec-pollo-al-horno-con-papas', 'cp-oregano', 3, 'mass_g'),
  ('rec-pollo-al-horno-con-papas-cp-limon', 'rec-pollo-al-horno-con-papas', 'cp-limon', 2, 'unit'),
  ('rec-pollo-al-horno-con-papas-cp-sal', 'rec-pollo-al-horno-con-papas', 'cp-sal', 2, 'mass_g'),
  ('rec-lentejas-con-arroz-cp-lentejas', 'rec-lentejas-con-arroz', 'cp-lentejas', 250, 'mass_g'),
  ('rec-lentejas-con-arroz-cp-arroz', 'rec-lentejas-con-arroz', 'cp-arroz', 200, 'mass_g'),
  ('rec-lentejas-con-arroz-cp-cebolla-blanca', 'rec-lentejas-con-arroz', 'cp-cebolla-blanca', 2, 'unit'),
  ('rec-lentejas-con-arroz-cp-aceite-de-oliva', 'rec-lentejas-con-arroz', 'cp-aceite-de-oliva', 45, 'volume_ml'),
  ('rec-lentejas-con-arroz-cp-sal', 'rec-lentejas-con-arroz', 'cp-sal', 2, 'mass_g'),
  ('rec-manzana-con-yogur-cp-manzana', 'rec-manzana-con-yogur', 'cp-manzana', 2, 'unit'),
  ('rec-manzana-con-yogur-cp-yogur-natural', 'rec-manzana-con-yogur', 'cp-yogur-natural', 200, 'mass_g'),
  ('rec-manzana-con-yogur-cp-azucar', 'rec-manzana-con-yogur', 'cp-azucar', 10, 'mass_g')
on conflict do nothing;

insert into public.commercial_product (id, canonical_product_id, store_id, brand, package_label, package_quantity, package_unit) values
  ('com-walmart-pechuga-de-pollo-1000', 'cp-pechuga-de-pollo', 'store-walmart', 'Bachoco', 'Pechuga Bachoco 1 kg', 1000, 'mass_g'),
  ('com-soriana-pechuga-de-pollo-900', 'cp-pechuga-de-pollo', 'store-soriana', 'Pilgrim''s', 'Pechuga Pilgrim''s 900 g', 900, 'mass_g'),
  ('com-alsuper-pechuga-de-pollo-1000', 'cp-pechuga-de-pollo', 'store-alsuper', null, 'Pechuga de pollo a granel 1 kg', 1000, 'mass_g'),
  ('com-soriana-huevo-18', 'cp-huevo', 'store-soriana', 'San Juan', 'Huevo blanco San Juan 18 pzas', 18, 'unit'),
  ('com-walmart-huevo-12', 'cp-huevo', 'store-walmart', 'Great Value', 'Huevo blanco Great Value 12 pzas', 12, 'unit'),
  ('com-walmart-frijol-pinto-1000', 'cp-frijol-pinto', 'store-walmart', 'Verde Valle', 'Frijol pinto Verde Valle 1 kg', 1000, 'mass_g'),
  ('com-walmart-arroz-1000', 'cp-arroz', 'store-walmart', 'Verde Valle', 'Arroz super extra Verde Valle 1 kg', 1000, 'mass_g'),
  ('com-soriana-arroz-900', 'cp-arroz', 'store-soriana', 'Schettino', 'Arroz Schettino 900 g', 900, 'mass_g'),
  ('com-soriana-pasta-spaghetti-200', 'cp-pasta-spaghetti', 'store-soriana', 'La Moderna', 'Spaghetti La Moderna 200 g', 200, 'mass_g'),
  ('com-walmart-avena-400', 'cp-avena', 'store-walmart', 'Quaker', 'Avena Quaker 400 g', 400, 'mass_g'),
  ('com-walmart-tortilla-de-maiz-1000', 'cp-tortilla-de-maiz', 'store-walmart', null, 'Tortilla de maiz 1 kg', 1000, 'mass_g'),
  ('com-walmart-jitomate-1000', 'cp-jitomate', 'store-walmart', null, 'Jitomate saladet por kg', 1000, 'mass_g'),
  ('com-walmart-cebolla-blanca-1', 'cp-cebolla-blanca', 'store-walmart', null, 'Cebolla blanca pieza', 1, 'unit'),
  ('com-alsuper-ajo-dientes-30', 'cp-ajo-dientes', 'store-alsuper', null, 'Ajo malla 3 cabezas (aprox. 30 dientes)', 30, 'unit'),
  ('com-alsuper-chile-serrano-10', 'cp-chile-serrano', 'store-alsuper', null, 'Chile serrano 10 pzas', 10, 'unit'),
  ('com-alsuper-cilantro-50', 'cp-cilantro', 'store-alsuper', null, 'Cilantro manojo 50 g', 50, 'mass_g'),
  ('com-walmart-platano-6', 'cp-platano', 'store-walmart', null, 'Platano tabasco 6 pzas', 6, 'unit'),
  ('com-walmart-leche-entera-1000', 'cp-leche-entera', 'store-walmart', 'Lala', 'Leche entera Lala 1 L', 1000, 'volume_ml'),
  ('com-alsuper-leche-entera-1000', 'cp-leche-entera', 'store-alsuper', 'Alpura', 'Leche entera Alpura 1 L', 1000, 'volume_ml'),
  ('com-soriana-queso-fresco-400', 'cp-queso-fresco', 'store-soriana', 'Nochebuena', 'Queso fresco Nochebuena 400 g', 400, 'mass_g'),
  ('com-soriana-crema-450', 'cp-crema', 'store-soriana', 'Lala', 'Crema Lala 450 ml', 450, 'volume_ml'),
  ('com-alsuper-aceite-vegetal-1000', 'cp-aceite-vegetal', 'store-alsuper', 'Nutrioli', 'Aceite Nutrioli 1 L', 1000, 'volume_ml'),
  ('com-alsuper-sal-1000', 'cp-sal', 'store-alsuper', 'La Fina', 'Sal La Fina 1 kg', 1000, 'mass_g'),
  ('com-walmart-carne-molida-de-res-1000', 'cp-carne-molida-de-res', 'store-walmart', null, 'Carne molida de res 1 kg', 1000, 'mass_g'),
  ('com-soriana-carne-molida-de-res-1000', 'cp-carne-molida-de-res', 'store-soriana', null, 'Carne molida de res 1 kg', 1000, 'mass_g'),
  ('com-alsuper-carne-molida-de-res-1000', 'cp-carne-molida-de-res', 'store-alsuper', null, 'Carne molida de res 1 kg', 1000, 'mass_g'),
  ('com-walmart-atun-en-agua-140', 'cp-atun-en-agua', 'store-walmart', 'Dolores', 'Atún Dolores en agua 140 g', 140, 'mass_g'),
  ('com-soriana-atun-en-agua-140', 'cp-atun-en-agua', 'store-soriana', 'Dolores', 'Atún Dolores en agua 140 g', 140, 'mass_g'),
  ('com-alsuper-atun-en-agua-140', 'cp-atun-en-agua', 'store-alsuper', 'Dolores', 'Atún Dolores en agua 140 g', 140, 'mass_g'),
  ('com-walmart-tofu-firme-400', 'cp-tofu-firme', 'store-walmart', 'Soyarroz', 'Tofu firme 400 g', 400, 'mass_g'),
  ('com-soriana-tofu-firme-400', 'cp-tofu-firme', 'store-soriana', 'Soyarroz', 'Tofu firme 400 g', 400, 'mass_g'),
  ('com-alsuper-tofu-firme-400', 'cp-tofu-firme', 'store-alsuper', 'Soyarroz', 'Tofu firme 400 g', 400, 'mass_g'),
  ('com-walmart-lentejas-500', 'cp-lentejas', 'store-walmart', 'Verde Valle', 'Lenteja Verde Valle 500 g', 500, 'mass_g'),
  ('com-soriana-lentejas-500', 'cp-lentejas', 'store-soriana', 'Verde Valle', 'Lenteja Verde Valle 500 g', 500, 'mass_g'),
  ('com-alsuper-lentejas-500', 'cp-lentejas', 'store-alsuper', 'Verde Valle', 'Lenteja Verde Valle 500 g', 500, 'mass_g'),
  ('com-walmart-garbanzo-500', 'cp-garbanzo', 'store-walmart', 'Verde Valle', 'Garbanzo Verde Valle 500 g', 500, 'mass_g'),
  ('com-soriana-garbanzo-500', 'cp-garbanzo', 'store-soriana', 'Verde Valle', 'Garbanzo Verde Valle 500 g', 500, 'mass_g'),
  ('com-alsuper-garbanzo-500', 'cp-garbanzo', 'store-alsuper', 'Verde Valle', 'Garbanzo Verde Valle 500 g', 500, 'mass_g'),
  ('com-walmart-bolillo-1', 'cp-bolillo', 'store-walmart', null, 'Bolillo pieza', 1, 'unit'),
  ('com-soriana-bolillo-1', 'cp-bolillo', 'store-soriana', null, 'Bolillo pieza', 1, 'unit'),
  ('com-alsuper-bolillo-1', 'cp-bolillo', 'store-alsuper', null, 'Bolillo pieza', 1, 'unit'),
  ('com-walmart-pan-de-caja-680', 'cp-pan-de-caja', 'store-walmart', 'Bimbo', 'Pan blanco Bimbo 680 g', 680, 'mass_g'),
  ('com-soriana-pan-de-caja-680', 'cp-pan-de-caja', 'store-soriana', 'Bimbo', 'Pan blanco Bimbo 680 g', 680, 'mass_g'),
  ('com-alsuper-pan-de-caja-680', 'cp-pan-de-caja', 'store-alsuper', 'Bimbo', 'Pan blanco Bimbo 680 g', 680, 'mass_g'),
  ('com-walmart-pasta-de-codo-200', 'cp-pasta-de-codo', 'store-walmart', 'La Moderna', 'Pasta codo La Moderna 200 g', 200, 'mass_g'),
  ('com-soriana-pasta-de-codo-200', 'cp-pasta-de-codo', 'store-soriana', 'La Moderna', 'Pasta codo La Moderna 200 g', 200, 'mass_g'),
  ('com-alsuper-pasta-de-codo-200', 'cp-pasta-de-codo', 'store-alsuper', 'La Moderna', 'Pasta codo La Moderna 200 g', 200, 'mass_g'),
  ('com-walmart-fideo-200', 'cp-fideo', 'store-walmart', 'La Moderna', 'Fideo La Moderna 200 g', 200, 'mass_g'),
  ('com-soriana-fideo-200', 'cp-fideo', 'store-soriana', 'La Moderna', 'Fideo La Moderna 200 g', 200, 'mass_g'),
  ('com-alsuper-fideo-200', 'cp-fideo', 'store-alsuper', 'La Moderna', 'Fideo La Moderna 200 g', 200, 'mass_g'),
  ('com-walmart-tortilla-de-harina-570', 'cp-tortilla-de-harina', 'store-walmart', 'Tía Rosa', 'Tortillas de harina Tía Rosa 570 g', 570, 'mass_g'),
  ('com-soriana-tortilla-de-harina-570', 'cp-tortilla-de-harina', 'store-soriana', 'Tía Rosa', 'Tortillas de harina Tía Rosa 570 g', 570, 'mass_g'),
  ('com-alsuper-tortilla-de-harina-570', 'cp-tortilla-de-harina', 'store-alsuper', 'Tía Rosa', 'Tortillas de harina Tía Rosa 570 g', 570, 'mass_g'),
  ('com-walmart-papa-1000', 'cp-papa', 'store-walmart', null, 'Papa blanca 1 kg', 1000, 'mass_g'),
  ('com-soriana-papa-1000', 'cp-papa', 'store-soriana', null, 'Papa blanca 1 kg', 1000, 'mass_g'),
  ('com-alsuper-papa-1000', 'cp-papa', 'store-alsuper', null, 'Papa blanca 1 kg', 1000, 'mass_g'),
  ('com-walmart-zanahoria-1000', 'cp-zanahoria', 'store-walmart', null, 'Zanahoria 1 kg', 1000, 'mass_g'),
  ('com-soriana-zanahoria-1000', 'cp-zanahoria', 'store-soriana', null, 'Zanahoria 1 kg', 1000, 'mass_g'),
  ('com-alsuper-zanahoria-1000', 'cp-zanahoria', 'store-alsuper', null, 'Zanahoria 1 kg', 1000, 'mass_g'),
  ('com-walmart-calabacita-1000', 'cp-calabacita', 'store-walmart', null, 'Calabacita italiana 1 kg', 1000, 'mass_g'),
  ('com-soriana-calabacita-1000', 'cp-calabacita', 'store-soriana', null, 'Calabacita italiana 1 kg', 1000, 'mass_g'),
  ('com-alsuper-calabacita-1000', 'cp-calabacita', 'store-alsuper', null, 'Calabacita italiana 1 kg', 1000, 'mass_g'),
  ('com-walmart-brocoli-500', 'cp-brocoli', 'store-walmart', null, 'Brócoli 500 g', 500, 'mass_g'),
  ('com-soriana-brocoli-500', 'cp-brocoli', 'store-soriana', null, 'Brócoli 500 g', 500, 'mass_g'),
  ('com-alsuper-brocoli-500', 'cp-brocoli', 'store-alsuper', null, 'Brócoli 500 g', 500, 'mass_g'),
  ('com-walmart-chile-poblano-1', 'cp-chile-poblano', 'store-walmart', null, 'Chile poblano pieza', 1, 'unit'),
  ('com-soriana-chile-poblano-1', 'cp-chile-poblano', 'store-soriana', null, 'Chile poblano pieza', 1, 'unit'),
  ('com-alsuper-chile-poblano-1', 'cp-chile-poblano', 'store-alsuper', null, 'Chile poblano pieza', 1, 'unit'),
  ('com-walmart-pimiento-morron-1', 'cp-pimiento-morron', 'store-walmart', null, 'Pimiento morrón rojo pieza', 1, 'unit'),
  ('com-soriana-pimiento-morron-1', 'cp-pimiento-morron', 'store-soriana', null, 'Pimiento morrón rojo pieza', 1, 'unit'),
  ('com-alsuper-pimiento-morron-1', 'cp-pimiento-morron', 'store-alsuper', null, 'Pimiento morrón rojo pieza', 1, 'unit'),
  ('com-walmart-lechuga-1', 'cp-lechuga', 'store-walmart', null, 'Lechuga romana pieza', 1, 'unit'),
  ('com-soriana-lechuga-1', 'cp-lechuga', 'store-soriana', null, 'Lechuga romana pieza', 1, 'unit'),
  ('com-alsuper-lechuga-1', 'cp-lechuga', 'store-alsuper', null, 'Lechuga romana pieza', 1, 'unit'),
  ('com-walmart-aguacate-1', 'cp-aguacate', 'store-walmart', null, 'Aguacate Hass pieza', 1, 'unit'),
  ('com-soriana-aguacate-1', 'cp-aguacate', 'store-soriana', null, 'Aguacate Hass pieza', 1, 'unit'),
  ('com-alsuper-aguacate-1', 'cp-aguacate', 'store-alsuper', null, 'Aguacate Hass pieza', 1, 'unit'),
  ('com-walmart-limon-20', 'cp-limon', 'store-walmart', null, 'Limón con semilla bolsa 20 piezas', 20, 'unit'),
  ('com-soriana-limon-20', 'cp-limon', 'store-soriana', null, 'Limón con semilla bolsa 20 piezas', 20, 'unit'),
  ('com-alsuper-limon-20', 'cp-limon', 'store-alsuper', null, 'Limón con semilla bolsa 20 piezas', 20, 'unit'),
  ('com-walmart-manzana-6', 'cp-manzana', 'store-walmart', null, 'Manzana roja bolsa 6 piezas', 6, 'unit'),
  ('com-soriana-manzana-6', 'cp-manzana', 'store-soriana', null, 'Manzana roja bolsa 6 piezas', 6, 'unit'),
  ('com-alsuper-manzana-6', 'cp-manzana', 'store-alsuper', null, 'Manzana roja bolsa 6 piezas', 6, 'unit'),
  ('com-walmart-queso-oaxaca-400', 'cp-queso-oaxaca', 'store-walmart', 'Lala', 'Queso Oaxaca Lala 400 g', 400, 'mass_g'),
  ('com-soriana-queso-oaxaca-400', 'cp-queso-oaxaca', 'store-soriana', 'Lala', 'Queso Oaxaca Lala 400 g', 400, 'mass_g'),
  ('com-alsuper-queso-oaxaca-400', 'cp-queso-oaxaca', 'store-alsuper', 'Lala', 'Queso Oaxaca Lala 400 g', 400, 'mass_g'),
  ('com-walmart-yogur-natural-1000', 'cp-yogur-natural', 'store-walmart', 'Yoplait', 'Yoghurt natural Yoplait 1 kg', 1000, 'mass_g'),
  ('com-soriana-yogur-natural-1000', 'cp-yogur-natural', 'store-soriana', 'Yoplait', 'Yoghurt natural Yoplait 1 kg', 1000, 'mass_g'),
  ('com-alsuper-yogur-natural-1000', 'cp-yogur-natural', 'store-alsuper', 'Yoplait', 'Yoghurt natural Yoplait 1 kg', 1000, 'mass_g'),
  ('com-walmart-mantequilla-90', 'cp-mantequilla', 'store-walmart', 'Gloria', 'Mantequilla sin sal Gloria 90 g', 90, 'mass_g'),
  ('com-soriana-mantequilla-90', 'cp-mantequilla', 'store-soriana', 'Gloria', 'Mantequilla sin sal Gloria 90 g', 90, 'mass_g'),
  ('com-alsuper-mantequilla-90', 'cp-mantequilla', 'store-alsuper', 'Gloria', 'Mantequilla sin sal Gloria 90 g', 90, 'mass_g'),
  ('com-walmart-salsa-de-soya-148', 'cp-salsa-de-soya', 'store-walmart', 'Kikkoman', 'Salsa de soya Kikkoman 148 ml', 148, 'volume_ml'),
  ('com-soriana-salsa-de-soya-148', 'cp-salsa-de-soya', 'store-soriana', 'Kikkoman', 'Salsa de soya Kikkoman 148 ml', 148, 'volume_ml'),
  ('com-alsuper-salsa-de-soya-148', 'cp-salsa-de-soya', 'store-alsuper', 'Kikkoman', 'Salsa de soya Kikkoman 148 ml', 148, 'volume_ml'),
  ('com-walmart-oregano-15', 'cp-oregano', 'store-walmart', 'McCormick', 'Orégano McCormick 15 g', 15, 'mass_g'),
  ('com-soriana-oregano-15', 'cp-oregano', 'store-soriana', 'McCormick', 'Orégano McCormick 15 g', 15, 'mass_g'),
  ('com-alsuper-oregano-15', 'cp-oregano', 'store-alsuper', 'McCormick', 'Orégano McCormick 15 g', 15, 'mass_g'),
  ('com-walmart-azucar-1000', 'cp-azucar', 'store-walmart', 'Zulka', 'Azúcar estándar Zulka 1 kg', 1000, 'mass_g'),
  ('com-soriana-azucar-1000', 'cp-azucar', 'store-soriana', 'Zulka', 'Azúcar estándar Zulka 1 kg', 1000, 'mass_g'),
  ('com-alsuper-azucar-1000', 'cp-azucar', 'store-alsuper', 'Zulka', 'Azúcar estándar Zulka 1 kg', 1000, 'mass_g'),
  ('com-walmart-aceite-de-oliva-500', 'cp-aceite-de-oliva', 'store-walmart', 'Carbonell', 'Aceite de oliva extra virgen Carbonell 500 ml', 500, 'volume_ml'),
  ('com-soriana-aceite-de-oliva-500', 'cp-aceite-de-oliva', 'store-soriana', 'Carbonell', 'Aceite de oliva extra virgen Carbonell 500 ml', 500, 'volume_ml'),
  ('com-alsuper-aceite-de-oliva-500', 'cp-aceite-de-oliva', 'store-alsuper', 'Carbonell', 'Aceite de oliva extra virgen Carbonell 500 ml', 500, 'volume_ml'),
  ('com-walmart-pure-de-tomate-210', 'cp-pure-de-tomate', 'store-walmart', 'Del Fuerte', 'Puré de tomate Del Fuerte 210 g', 210, 'mass_g'),
  ('com-soriana-pure-de-tomate-210', 'cp-pure-de-tomate', 'store-soriana', 'Del Fuerte', 'Puré de tomate Del Fuerte 210 g', 210, 'mass_g'),
  ('com-alsuper-pure-de-tomate-210', 'cp-pure-de-tomate', 'store-alsuper', 'Del Fuerte', 'Puré de tomate Del Fuerte 210 g', 210, 'mass_g')
on conflict do nothing;

insert into public.price_observation (id, commercial_product_id, price_cents, observed_at) values
  ('price-com-walmart-pechuga-de-pollo-1000', 'com-walmart-pechuga-de-pollo-1000', 13900, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-pechuga-de-pollo-900', 'com-soriana-pechuga-de-pollo-900', 12990, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-pechuga-de-pollo-1000', 'com-alsuper-pechuga-de-pollo-1000', 14500, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-huevo-18', 'com-soriana-huevo-18', 5490, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-huevo-12', 'com-walmart-huevo-12', 3990, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-frijol-pinto-1000', 'com-walmart-frijol-pinto-1000', 3990, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-arroz-1000', 'com-walmart-arroz-1000', 3290, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-arroz-900', 'com-soriana-arroz-900', 3150, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-pasta-spaghetti-200', 'com-soriana-pasta-spaghetti-200', 1290, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-avena-400', 'com-walmart-avena-400', 3490, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-tortilla-de-maiz-1000', 'com-walmart-tortilla-de-maiz-1000', 2400, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-jitomate-1000', 'com-walmart-jitomate-1000', 3490, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-cebolla-blanca-1', 'com-walmart-cebolla-blanca-1', 900, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-ajo-dientes-30', 'com-alsuper-ajo-dientes-30', 2990, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-chile-serrano-10', 'com-alsuper-chile-serrano-10', 1500, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-cilantro-50', 'com-alsuper-cilantro-50', 800, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-platano-6', 'com-walmart-platano-6', 2190, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-leche-entera-1000', 'com-walmart-leche-entera-1000', 2890, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-leche-entera-1000', 'com-alsuper-leche-entera-1000', 2990, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-queso-fresco-400', 'com-soriana-queso-fresco-400', 5990, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-crema-450', 'com-soriana-crema-450', 3290, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-aceite-vegetal-1000', 'com-alsuper-aceite-vegetal-1000', 4590, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-sal-1000', 'com-alsuper-sal-1000', 1290, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-carne-molida-de-res-1000', 'com-walmart-carne-molida-de-res-1000', 17900, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-carne-molida-de-res-1000', 'com-soriana-carne-molida-de-res-1000', 17360, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-carne-molida-de-res-1000', 'com-alsuper-carne-molida-de-res-1000', 18800, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-atun-en-agua-140', 'com-walmart-atun-en-agua-140', 2450, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-atun-en-agua-140', 'com-soriana-atun-en-agua-140', 2380, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-atun-en-agua-140', 'com-alsuper-atun-en-agua-140', 2570, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-tofu-firme-400', 'com-walmart-tofu-firme-400', 4590, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-tofu-firme-400', 'com-soriana-tofu-firme-400', 4450, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-tofu-firme-400', 'com-alsuper-tofu-firme-400', 4820, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-lentejas-500', 'com-walmart-lentejas-500', 3390, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-lentejas-500', 'com-soriana-lentejas-500', 3290, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-lentejas-500', 'com-alsuper-lentejas-500', 3560, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-garbanzo-500', 'com-walmart-garbanzo-500', 3890, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-garbanzo-500', 'com-soriana-garbanzo-500', 3770, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-garbanzo-500', 'com-alsuper-garbanzo-500', 4080, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-bolillo-1', 'com-walmart-bolillo-1', 350, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-bolillo-1', 'com-soriana-bolillo-1', 340, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-bolillo-1', 'com-alsuper-bolillo-1', 370, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-pan-de-caja-680', 'com-walmart-pan-de-caja-680', 5250, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-pan-de-caja-680', 'com-soriana-pan-de-caja-680', 5090, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-pan-de-caja-680', 'com-alsuper-pan-de-caja-680', 5510, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-pasta-de-codo-200', 'com-walmart-pasta-de-codo-200', 1590, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-pasta-de-codo-200', 'com-soriana-pasta-de-codo-200', 1540, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-pasta-de-codo-200', 'com-alsuper-pasta-de-codo-200', 1670, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-fideo-200', 'com-walmart-fideo-200', 1490, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-fideo-200', 'com-soriana-fideo-200', 1450, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-fideo-200', 'com-alsuper-fideo-200', 1560, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-tortilla-de-harina-570', 'com-walmart-tortilla-de-harina-570', 4290, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-tortilla-de-harina-570', 'com-soriana-tortilla-de-harina-570', 4160, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-tortilla-de-harina-570', 'com-alsuper-tortilla-de-harina-570', 4500, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-papa-1000', 'com-walmart-papa-1000', 3290, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-papa-1000', 'com-soriana-papa-1000', 3190, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-papa-1000', 'com-alsuper-papa-1000', 3450, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-zanahoria-1000', 'com-walmart-zanahoria-1000', 2390, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-zanahoria-1000', 'com-soriana-zanahoria-1000', 2320, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-zanahoria-1000', 'com-alsuper-zanahoria-1000', 2510, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-calabacita-1000', 'com-walmart-calabacita-1000', 3490, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-calabacita-1000', 'com-soriana-calabacita-1000', 3390, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-calabacita-1000', 'com-alsuper-calabacita-1000', 3660, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-brocoli-500', 'com-walmart-brocoli-500', 2990, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-brocoli-500', 'com-soriana-brocoli-500', 2900, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-brocoli-500', 'com-alsuper-brocoli-500', 3140, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-chile-poblano-1', 'com-walmart-chile-poblano-1', 590, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-chile-poblano-1', 'com-soriana-chile-poblano-1', 570, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-chile-poblano-1', 'com-alsuper-chile-poblano-1', 620, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-pimiento-morron-1', 'com-walmart-pimiento-morron-1', 1190, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-pimiento-morron-1', 'com-soriana-pimiento-morron-1', 1150, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-pimiento-morron-1', 'com-alsuper-pimiento-morron-1', 1250, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-lechuga-1', 'com-walmart-lechuga-1', 2490, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-lechuga-1', 'com-soriana-lechuga-1', 2420, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-lechuga-1', 'com-alsuper-lechuga-1', 2610, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-aguacate-1', 'com-walmart-aguacate-1', 1490, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-aguacate-1', 'com-soriana-aguacate-1', 1450, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-aguacate-1', 'com-alsuper-aguacate-1', 1560, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-limon-20', 'com-walmart-limon-20', 4490, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-limon-20', 'com-soriana-limon-20', 4360, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-limon-20', 'com-alsuper-limon-20', 4710, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-manzana-6', 'com-walmart-manzana-6', 5490, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-manzana-6', 'com-soriana-manzana-6', 5330, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-manzana-6', 'com-alsuper-manzana-6', 5760, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-queso-oaxaca-400', 'com-walmart-queso-oaxaca-400', 8890, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-queso-oaxaca-400', 'com-soriana-queso-oaxaca-400', 8620, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-queso-oaxaca-400', 'com-alsuper-queso-oaxaca-400', 9330, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-yogur-natural-1000', 'com-walmart-yogur-natural-1000', 4490, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-yogur-natural-1000', 'com-soriana-yogur-natural-1000', 4360, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-yogur-natural-1000', 'com-alsuper-yogur-natural-1000', 4710, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-mantequilla-90', 'com-walmart-mantequilla-90', 3190, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-mantequilla-90', 'com-soriana-mantequilla-90', 3090, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-mantequilla-90', 'com-alsuper-mantequilla-90', 3350, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-salsa-de-soya-148', 'com-walmart-salsa-de-soya-148', 3890, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-salsa-de-soya-148', 'com-soriana-salsa-de-soya-148', 3770, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-salsa-de-soya-148', 'com-alsuper-salsa-de-soya-148', 4080, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-oregano-15', 'com-walmart-oregano-15', 1790, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-oregano-15', 'com-soriana-oregano-15', 1740, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-oregano-15', 'com-alsuper-oregano-15', 1880, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-azucar-1000', 'com-walmart-azucar-1000', 3490, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-azucar-1000', 'com-soriana-azucar-1000', 3390, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-azucar-1000', 'com-alsuper-azucar-1000', 3660, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-aceite-de-oliva-500', 'com-walmart-aceite-de-oliva-500', 12900, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-aceite-de-oliva-500', 'com-soriana-aceite-de-oliva-500', 12510, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-aceite-de-oliva-500', 'com-alsuper-aceite-de-oliva-500', 13540, '2026-09-20T12:00:00Z'),
  ('price-com-walmart-pure-de-tomate-210', 'com-walmart-pure-de-tomate-210', 1190, '2026-09-20T12:00:00Z'),
  ('price-com-soriana-pure-de-tomate-210', 'com-soriana-pure-de-tomate-210', 1150, '2026-09-20T12:00:00Z'),
  ('price-com-alsuper-pure-de-tomate-210', 'com-alsuper-pure-de-tomate-210', 1250, '2026-09-20T12:00:00Z')
on conflict do nothing;

